/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdConfigInput {
    /// Use anonymous binds when performing LDAP group searches (if true the initial credentials will still be used for the initial connection test).
    #[serde(rename = "anonymous_group_search", skip_serializing_if = "Option::is_none")]
    pub anonymous_group_search: Option<bool>,
    /// LDAP DN for searching for the user DN (optional)
    #[serde(rename = "binddn", skip_serializing_if = "Option::is_none")]
    pub binddn: Option<String>,
    /// LDAP password for searching for the user DN (optional)
    #[serde(rename = "bindpass", skip_serializing_if = "Option::is_none")]
    pub bindpass: Option<String>,
    /// If true, case sensitivity will be used when comparing usernames and groups for matching policies.
    #[serde(rename = "case_sensitive_names", skip_serializing_if = "Option::is_none")]
    pub case_sensitive_names: Option<bool>,
    /// CA certificate to use when verifying LDAP server certificate, must be x509 PEM encoded (optional)
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    /// Client certificate to provide to the LDAP server, must be x509 PEM encoded (optional)
    #[serde(rename = "client_tls_cert", skip_serializing_if = "Option::is_none")]
    pub client_tls_cert: Option<String>,
    /// Client certificate key to provide to the LDAP server, must be x509 PEM encoded (optional)
    #[serde(rename = "client_tls_key", skip_serializing_if = "Option::is_none")]
    pub client_tls_key: Option<String>,
    /// Denies an unauthenticated LDAP bind request if the user's password is empty; defaults to true
    #[serde(rename = "deny_null_bind", skip_serializing_if = "Option::is_none")]
    pub deny_null_bind: Option<bool>,
    /// Use anonymous bind to discover the bind DN of a user (optional)
    #[serde(rename = "discoverdn", skip_serializing_if = "Option::is_none")]
    pub discoverdn: Option<bool>,
    /// Text to insert the password into, ex. \"customPrefix{{PASSWORD}}customSuffix\".
    #[serde(rename = "formatter", skip_serializing_if = "Option::is_none")]
    pub formatter: Option<String>,
    /// LDAP attribute to follow on objects returned by <groupfilter> in order to enumerate user group membership. Examples: \"cn\" or \"memberOf\", etc. Default: cn
    #[serde(rename = "groupattr", skip_serializing_if = "Option::is_none")]
    pub groupattr: Option<String>,
    /// LDAP search base to use for group membership search (eg: ou=Groups,dc=example,dc=org)
    #[serde(rename = "groupdn", skip_serializing_if = "Option::is_none")]
    pub groupdn: Option<String>,
    /// Go template for querying group membership of user (optional) The template can access the following context variables: UserDN, Username Example: (&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}})) Default: (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))
    #[serde(rename = "groupfilter", skip_serializing_if = "Option::is_none")]
    pub groupfilter: Option<String>,
    /// Skip LDAP server SSL Certificate verification - VERY insecure (optional)
    #[serde(rename = "insecure_tls", skip_serializing_if = "Option::is_none")]
    pub insecure_tls: Option<bool>,
    /// The number of seconds after a Vault rotation where, if Active Directory shows a later rotation, it should be considered out-of-band.
    #[serde(rename = "last_rotation_tolerance", skip_serializing_if = "Option::is_none")]
    pub last_rotation_tolerance: Option<i32>,
    /// The desired length of passwords that Vault generates.
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    /// In seconds, the maximum password time-to-live.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Name of the password policy to use to generate passwords.
    #[serde(rename = "password_policy", skip_serializing_if = "Option::is_none")]
    pub password_policy: Option<String>,
    /// Timeout, in seconds, for the connection when making requests against the server before returning back an error.
    #[serde(rename = "request_timeout", skip_serializing_if = "Option::is_none")]
    pub request_timeout: Option<i32>,
    /// Issue a StartTLS command after establishing unencrypted connection (optional)
    #[serde(rename = "starttls", skip_serializing_if = "Option::is_none")]
    pub starttls: Option<bool>,
    /// Maximum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12'
    #[serde(rename = "tls_max_version", skip_serializing_if = "Option::is_none")]
    pub tls_max_version: Option<TlsMaxVersion>,
    /// Minimum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12'
    #[serde(rename = "tls_min_version", skip_serializing_if = "Option::is_none")]
    pub tls_min_version: Option<TlsMinVersion>,
    /// In seconds, the default password time-to-live.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// Enables userPrincipalDomain login with [username]@UPNDomain (optional)
    #[serde(rename = "upndomain", skip_serializing_if = "Option::is_none")]
    pub upndomain: Option<String>,
    /// LDAP URL to connect to (default: ldap://127.0.0.1). Multiple URLs can be specified by concatenating them with commas; they will be tried in-order.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// In Vault 1.1.1 a fix for handling group CN values of different cases unfortunately introduced a regression that could cause previously defined groups to not be found due to a change in the resulting name. If set true, the pre-1.1.1 behavior for matching group CNs will be used. This is only needed in some upgrade scenarios for backwards compatibility. It is enabled by default if the config is upgraded but disabled by default on new configurations.
    #[serde(rename = "use_pre111_group_cn_behavior", skip_serializing_if = "Option::is_none")]
    pub use_pre111_group_cn_behavior: Option<bool>,
    /// If true, use the Active Directory tokenGroups constructed attribute of the user to find the group memberships. This will find all security groups including nested ones.
    #[serde(rename = "use_token_groups", skip_serializing_if = "Option::is_none")]
    pub use_token_groups: Option<bool>,
    /// Attribute used for users (default: cn)
    #[serde(rename = "userattr", skip_serializing_if = "Option::is_none")]
    pub userattr: Option<String>,
    /// LDAP domain to use for users (eg: ou=People,dc=example,dc=org)
    #[serde(rename = "userdn", skip_serializing_if = "Option::is_none")]
    pub userdn: Option<String>,
}

impl AdConfigInput {
    pub fn new() -> AdConfigInput {
        AdConfigInput {
            anonymous_group_search: None,
            binddn: None,
            bindpass: None,
            case_sensitive_names: None,
            certificate: None,
            client_tls_cert: None,
            client_tls_key: None,
            deny_null_bind: None,
            discoverdn: None,
            formatter: None,
            groupattr: None,
            groupdn: None,
            groupfilter: None,
            insecure_tls: None,
            last_rotation_tolerance: None,
            length: None,
            max_ttl: None,
            password_policy: None,
            request_timeout: None,
            starttls: None,
            tls_max_version: None,
            tls_min_version: None,
            ttl: None,
            upndomain: None,
            url: None,
            use_pre111_group_cn_behavior: None,
            use_token_groups: None,
            userattr: None,
            userdn: None,
        }
    }
}

/// Maximum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12'
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TlsMaxVersion {
    #[serde(rename = "tls10")]
    Tls10,
    #[serde(rename = "tls11")]
    Tls11,
    #[serde(rename = "tls12")]
    Tls12,
    #[serde(rename = "tls13")]
    Tls13,
}
/// Minimum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12'
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TlsMinVersion {
    #[serde(rename = "tls10")]
    Tls10,
    #[serde(rename = "tls11")]
    Tls11,
    #[serde(rename = "tls12")]
    Tls12,
    #[serde(rename = "tls13")]
    Tls13,
}

