/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdLibraryCheckOutInput {
    /// The length of time before the check-out will expire, in seconds.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl AdLibraryCheckOutInput {
    pub fn new() -> AdLibraryCheckOutInput {
        AdLibraryCheckOutInput {
            ttl: None,
        }
    }
}


