/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdLibraryCheckInInput {
    /// The username/logon name for the service accounts to check in.
    #[serde(rename = "service_account_names", skip_serializing_if = "Option::is_none")]
    pub service_account_names: Option<Vec<String>>,
}

impl AdLibraryCheckInInput {
    pub fn new() -> AdLibraryCheckInInput {
        AdLibraryCheckInInput {
            service_account_names: None,
        }
    }
}


