/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlicloudRole {
    /// JSON of policies to be dynamically applied to users of this role.
    #[serde(rename = "inline_policies", skip_serializing_if = "Option::is_none")]
    pub inline_policies: Option<String>,
    /// The maximum allowed lifetime of tokens issued using this role.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// The name and type of each remote policy to be applied. Example: \"name:AliyunRDSReadOnlyAccess,type:System\".
    #[serde(rename = "remote_policies", skip_serializing_if = "Option::is_none")]
    pub remote_policies: Option<Vec<String>>,
    /// ARN of the role to be assumed. If provided, inline_policies and remote_policies should be blank. At creation time, this role must have configured trusted actors, and the access key and secret that will be used to assume the role (in /config) must qualify as a trusted actor.
    #[serde(rename = "role_arn", skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    /// Duration in seconds after which the issued token should expire. Defaults to 0, in which case the value will fallback to the system/mount defaults.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl AlicloudRole {
    pub fn new() -> AlicloudRole {
        AlicloudRole {
            inline_policies: None,
            max_ttl: None,
            remote_policies: None,
            role_arn: None,
            ttl: None,
        }
    }
}


