/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsConfigLease {
    /// Default lease for roles.
    #[serde(rename = "lease", skip_serializing_if = "Option::is_none")]
    pub lease: Option<String>,
    /// Maximum time a credential is valid for.
    #[serde(rename = "lease_max", skip_serializing_if = "Option::is_none")]
    pub lease_max: Option<String>,
}

impl AwsConfigLease {
    pub fn new() -> AwsConfigLease {
        AwsConfigLease {
            lease: None,
            lease_max: None,
        }
    }
}


