/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsConfigRootInput {
    /// Access key with permission to create new keys.
    #[serde(rename = "access_key", skip_serializing_if = "Option::is_none")]
    pub access_key: Option<String>,
    /// Endpoint to custom IAM server URL
    #[serde(rename = "iam_endpoint", skip_serializing_if = "Option::is_none")]
    pub iam_endpoint: Option<String>,
    /// Maximum number of retries for recoverable exceptions of AWS APIs
    #[serde(rename = "max_retries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
    /// Region for API calls.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Secret key with permission to create new keys.
    #[serde(rename = "secret_key", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    /// Endpoint to custom STS server URL
    #[serde(rename = "sts_endpoint", skip_serializing_if = "Option::is_none")]
    pub sts_endpoint: Option<String>,
}

impl AwsConfigRootInput {
    pub fn new() -> AwsConfigRootInput {
        AwsConfigRootInput {
            access_key: None,
            iam_endpoint: None,
            max_retries: None,
            region: None,
            secret_key: None,
            sts_endpoint: None,
        }
    }
}


