/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsStsInput {
    /// ARN of role to assume when credential_type is assumed_role
    #[serde(rename = "role_arn", skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    /// Lifetime of the returned credentials in seconds
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl AwsStsInput {
    pub fn new() -> AwsStsInput {
        AwsStsInput {
            role_arn: None,
            ttl: None,
        }
    }
}


