/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureRoleInput {
    /// Application Object ID to use for static service principal credentials.
    #[serde(rename = "application_object_id", skip_serializing_if = "Option::is_none")]
    pub application_object_id: Option<String>,
    /// JSON list of Azure groups to add the service principal to.
    #[serde(rename = "azure_groups", skip_serializing_if = "Option::is_none")]
    pub azure_groups: Option<String>,
    /// JSON list of Azure roles to assign.
    #[serde(rename = "azure_roles", skip_serializing_if = "Option::is_none")]
    pub azure_roles: Option<String>,
    /// Maximum time a service principal. If not set or set to 0, will use system default.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Default lease for generated credentials. If not set or set to 0, will use system default.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl AzureRoleInput {
    pub fn new() -> AzureRoleInput {
        AzureRoleInput {
            application_object_id: None,
            azure_groups: None,
            azure_roles: None,
            max_ttl: None,
            ttl: None,
        }
    }
}


