/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsulRoleInput {
    /// Use ttl instead.
    #[serde(rename = "lease", skip_serializing_if = "Option::is_none")]
    pub lease: Option<i32>,
    /// Indicates that the token should not be replicated globally and instead be local to the current datacenter. Available in Consul 1.4 and above.
    #[serde(rename = "local", skip_serializing_if = "Option::is_none")]
    pub local: Option<bool>,
    /// Max TTL for the Consul token created from the role.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// List of policies to attach to the token. Required for Consul 1.4 or above.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// Policy document, base64 encoded. Required for 'client' tokens. Required for Consul pre-1.4.
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    /// Which type of token to create: 'client' or 'management'. If a 'management' token, the \"policy\" parameter is not required. Defaults to 'client'.
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    /// TTL for the Consul token created from the role.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl ConsulRoleInput {
    pub fn new() -> ConsulRoleInput {
        ConsulRoleInput {
            lease: None,
            local: None,
            max_ttl: None,
            policies: None,
            policy: None,
            token_type: None,
            ttl: None,
        }
    }
}


