/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseRoleInput {
    /// Specifies the database statements executed to create and configure a user. See the plugin's API page for more information on support and formatting for this parameter.
    #[serde(rename = "creation_statements", skip_serializing_if = "Option::is_none")]
    pub creation_statements: Option<Vec<String>>,
    /// Name of the database this role acts on.
    #[serde(rename = "db_name", skip_serializing_if = "Option::is_none")]
    pub db_name: Option<String>,
    /// Default ttl for role.
    #[serde(rename = "default_ttl", skip_serializing_if = "Option::is_none")]
    pub default_ttl: Option<i32>,
    /// Maximum time a credential is valid for
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Specifies the database statements to be executed to renew a user. Not every plugin type will support this functionality. See the plugin's API page for more information on support and formatting for this parameter.
    #[serde(rename = "renew_statements", skip_serializing_if = "Option::is_none")]
    pub renew_statements: Option<Vec<String>>,
    /// Specifies the database statements to be executed to revoke a user. See the plugin's API page for more information on support and formatting for this parameter.
    #[serde(rename = "revocation_statements", skip_serializing_if = "Option::is_none")]
    pub revocation_statements: Option<Vec<String>>,
    /// Specifies the database statements to be executed rollback a create operation in the event of an error. Not every plugin type will support this functionality. See the plugin's API page for more information on support and formatting for this parameter.
    #[serde(rename = "rollback_statements", skip_serializing_if = "Option::is_none")]
    pub rollback_statements: Option<Vec<String>>,
}

impl DatabaseRoleInput {
    pub fn new() -> DatabaseRoleInput {
        DatabaseRoleInput {
            creation_statements: None,
            db_name: None,
            default_ttl: None,
            max_ttl: None,
            renew_statements: None,
            revocation_statements: None,
            rollback_statements: None,
        }
    }
}


