/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseStaticRoleInput {
    /// Name of the database this role acts on.
    #[serde(rename = "db_name", skip_serializing_if = "Option::is_none")]
    pub db_name: Option<String>,
    /// Period for automatic credential rotation of the given username. Not valid unless used with \"username\".
    #[serde(rename = "rotation_period", skip_serializing_if = "Option::is_none")]
    pub rotation_period: Option<i32>,
    /// Specifies the database statements to be executed to rotate the accounts credentials. Not every plugin type will support this functionality. See the plugin's API page for more information on support and formatting for this parameter.
    #[serde(rename = "rotation_statements", skip_serializing_if = "Option::is_none")]
    pub rotation_statements: Option<Vec<String>>,
    /// Name of the static user account for Vault to manage. Requires \"rotation_period\" to be specified
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl DatabaseStaticRoleInput {
    pub fn new() -> DatabaseStaticRoleInput {
        DatabaseStaticRoleInput {
            db_name: None,
            rotation_period: None,
            rotation_statements: None,
            username: None,
        }
    }
}


