/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcpConfig {
    /// GCP IAM service account credentials JSON with permissions to create new service accounts and set IAM policies
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<String>,
    /// Maximum time a service account key is valid for. If <= 0, will use system default.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Default lease for generated keys. If <= 0, will use system default.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl GcpConfig {
    pub fn new() -> GcpConfig {
        GcpConfig {
            credentials: None,
            max_ttl: None,
            ttl: None,
        }
    }
}


