/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcpRolesetInput {
    /// Bindings configuration string.
    #[serde(rename = "bindings", skip_serializing_if = "Option::is_none")]
    pub bindings: Option<String>,
    /// Name of the GCP project that this roleset's service account will belong to.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// Type of secret generated for this role set. Defaults to 'access_token'
    #[serde(rename = "secret_type", skip_serializing_if = "Option::is_none")]
    pub secret_type: Option<String>,
    /// List of OAuth scopes to assign to credentials generated under this role set
    #[serde(rename = "token_scopes", skip_serializing_if = "Option::is_none")]
    pub token_scopes: Option<Vec<String>>,
}

impl GcpRolesetInput {
    pub fn new() -> GcpRolesetInput {
        GcpRolesetInput {
            bindings: None,
            project: None,
            secret_type: None,
            token_scopes: None,
        }
    }
}


