/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcpKeyInput {
    /// Private key algorithm for service account key - defaults to KEY_ALG_RSA_2048\"
    #[serde(rename = "key_algorithm", skip_serializing_if = "Option::is_none")]
    pub key_algorithm: Option<String>,
    /// Private key type for service account key - defaults to TYPE_GOOGLE_CREDENTIALS_FILE\"
    #[serde(rename = "key_type", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<String>,
    /// Lifetime of the service account key
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl GcpKeyInput {
    pub fn new() -> GcpKeyInput {
        GcpKeyInput {
            key_algorithm: None,
            key_type: None,
            ttl: None,
        }
    }
}


