/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcpkmsReencryptInput {
    /// Optional data that, if specified, must also be provided during decryption.
    #[serde(rename = "additional_authenticated_data", skip_serializing_if = "Option::is_none")]
    pub additional_authenticated_data: Option<String>,
    /// Ciphertext to be re-encrypted to the latest key version. This must be ciphertext that Vault previously generated for this named key.
    #[serde(rename = "ciphertext", skip_serializing_if = "Option::is_none")]
    pub ciphertext: Option<String>,
    /// Integer version of the crypto key version to use for the new encryption. If unspecified, this defaults to the latest active crypto key version.
    #[serde(rename = "key_version", skip_serializing_if = "Option::is_none")]
    pub key_version: Option<i32>,
}

impl GcpkmsReencryptInput {
    pub fn new() -> GcpkmsReencryptInput {
        GcpkmsReencryptInput {
            additional_authenticated_data: None,
            ciphertext: None,
            key_version: None,
        }
    }
}


