/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcpkmsVerifyInput {
    /// Digest to verify. This digest must use the same SHA algorithm as the underlying Cloud KMS key. The digest must be the base64-encoded binary value. This field is required.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,
    /// Integer version of the crypto key version to use for verification. This field is required.
    #[serde(rename = "key_version", skip_serializing_if = "Option::is_none")]
    pub key_version: Option<i32>,
    /// Base64-encoded signature to use for verification. This field is required.
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl GcpkmsVerifyInput {
    pub fn new() -> GcpkmsVerifyInput {
        GcpkmsVerifyInput {
            digest: None,
            key_version: None,
            signature: None,
        }
    }
}


