/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MongodbatlasRole {
    /// Whitelist entry in CIDR notation to be added for the API key. Optional for organization and project keys.
    #[serde(rename = "cidr_blocks", skip_serializing_if = "Option::is_none")]
    pub cidr_blocks: Option<Vec<String>>,
    /// IP address to be added to the whitelist for the API key. Optional for organization and project keys.
    #[serde(rename = "ip_addresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<Vec<String>>,
    /// The maximum allowed lifetime of credentials issued using this role.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Organization ID required for an organization API key
    #[serde(rename = "organization_id", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<String>,
    /// Project ID the project API key belongs to.
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// Roles assigned when an organization API Key is assigned to a project API key
    #[serde(rename = "project_roles", skip_serializing_if = "Option::is_none")]
    pub project_roles: Option<Vec<String>>,
    /// List of roles that the API Key should be granted. A minimum of one role must be provided. Any roles provided must be valid for the assigned Project, required for organization and project keys.
    #[serde(rename = "roles")]
    pub roles: Vec<String>,
    /// Duration in seconds after which the issued credential should expire. Defaults to 0, in which case the value will fallback to the system/mount defaults.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl MongodbatlasRole {
    pub fn new(roles: Vec<String>) -> MongodbatlasRole {
        MongodbatlasRole {
            cidr_blocks: None,
            ip_addresses: None,
            max_ttl: None,
            organization_id: None,
            project_id: None,
            project_roles: None,
            roles,
            ttl: None,
        }
    }
}


