/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MongodbatlasConfig {
    /// MongoDB Atlas Programmatic Private Key
    #[serde(rename = "private_key")]
    pub private_key: String,
    /// MongoDB Atlas Programmatic Public Key
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl MongodbatlasConfig {
    pub fn new(private_key: String, public_key: String) -> MongodbatlasConfig {
        MongodbatlasConfig {
            private_key,
            public_key,
        }
    }
}


