/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenldapStaticRoleInput {
    /// The distinguished name of the entry to manage.
    #[serde(rename = "dn", skip_serializing_if = "Option::is_none")]
    pub dn: Option<String>,
    /// Period for automatic credential rotation of the given entry.
    #[serde(rename = "rotation_period", skip_serializing_if = "Option::is_none")]
    pub rotation_period: Option<i32>,
    /// The time-to-live for the password.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// The username/logon name for the entry with which this role will be associated.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl OpenldapStaticRoleInput {
    pub fn new() -> OpenldapStaticRoleInput {
        OpenldapStaticRoleInput {
            dn: None,
            rotation_period: None,
            ttl: None,
            username: None,
        }
    }
}


