/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenldapRoleInput {
    /// LDIF string used to create new entities within OpenLDAP. This LDIF can be templated.
    #[serde(rename = "creation_ldif")]
    pub creation_ldif: String,
    /// Default TTL for dynamic credentials
    #[serde(rename = "default_ttl", skip_serializing_if = "Option::is_none")]
    pub default_ttl: Option<i32>,
    /// LDIF string used to delete entities created within OpenLDAP. This LDIF can be templated.
    #[serde(rename = "deletion_ldif")]
    pub deletion_ldif: String,
    /// Max TTL a dynamic credential can be extended to
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// LDIF string used to rollback changes in the event of a failure to create credentials. This LDIF can be templated.
    #[serde(rename = "rollback_ldif", skip_serializing_if = "Option::is_none")]
    pub rollback_ldif: Option<String>,
    /// The template used to create a username
    #[serde(rename = "username_template", skip_serializing_if = "Option::is_none")]
    pub username_template: Option<String>,
}

impl OpenldapRoleInput {
    pub fn new(creation_ldif: String, deletion_ldif: String) -> OpenldapRoleInput {
        OpenldapRoleInput {
            creation_ldif,
            default_ttl: None,
            deletion_ldif,
            max_ttl: None,
            rollback_ldif: None,
            username_template: None,
        }
    }
}


