/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RabbitmqConfigConnectionInput {
    /// RabbitMQ Management URI
    #[serde(rename = "connection_uri", skip_serializing_if = "Option::is_none")]
    pub connection_uri: Option<String>,
    /// Password of the provided RabbitMQ management user
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Name of the password policy to use to generate passwords for dynamic credentials.
    #[serde(rename = "password_policy", skip_serializing_if = "Option::is_none")]
    pub password_policy: Option<String>,
    /// Username of a RabbitMQ management administrator
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// If set, connection_uri is verified by actually connecting to the RabbitMQ management API
    #[serde(rename = "verify_connection", skip_serializing_if = "Option::is_none")]
    pub verify_connection: Option<bool>,
}

impl RabbitmqConfigConnectionInput {
    pub fn new() -> RabbitmqConfigConnectionInput {
        RabbitmqConfigConnectionInput {
            connection_uri: None,
            password: None,
            password_policy: None,
            username: None,
            verify_connection: None,
        }
    }
}


