/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RabbitmqRole {
    /// Comma-separated list of tags for this role.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    /// A nested map of virtual hosts and exchanges to topic permissions.
    #[serde(rename = "vhost_topics", skip_serializing_if = "Option::is_none")]
    pub vhost_topics: Option<String>,
    /// A map of virtual hosts to permissions.
    #[serde(rename = "vhosts", skip_serializing_if = "Option::is_none")]
    pub vhosts: Option<String>,
}

impl RabbitmqRole {
    pub fn new() -> RabbitmqRole {
        RabbitmqRole {
            tags: None,
            vhost_topics: None,
            vhosts: None,
        }
    }
}


