/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RabbitmqConfigLease {
    /// Duration after which the issued credentials should not be allowed to be renewed
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Duration before which the issued credentials needs renewal
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl RabbitmqConfigLease {
    pub fn new() -> RabbitmqConfigLease {
        RabbitmqConfigLease {
            max_ttl: None,
            ttl: None,
        }
    }
}


