/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshRoleInput {
    /// [Required for Dynamic type] [Not applicable for OTP type] [Not applicable for CA type] Admin user at remote host. The shared key being registered should be for this user and should have root privileges. Everytime a dynamic credential is being generated for other users, Vault uses this admin username to login to remote host and install the generated credential for the other user.
    #[serde(rename = "admin_user", skip_serializing_if = "Option::is_none")]
    pub admin_user: Option<String>,
    /// When supplied, this value specifies a signing algorithm for the key. Possible values: ssh-rsa, rsa-sha2-256, rsa-sha2-512.
    #[serde(rename = "algorithm_signer", skip_serializing_if = "Option::is_none")]
    pub algorithm_signer: Option<String>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If set, host certificates that are requested are allowed to use the base domains listed in \"allowed_domains\", e.g. \"example.com\". This is a separate option as in some cases this can be considered a security threat.
    #[serde(rename = "allow_bare_domains", skip_serializing_if = "Option::is_none")]
    pub allow_bare_domains: Option<bool>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If set, certificates are allowed to be signed for use as a 'host'.
    #[serde(rename = "allow_host_certificates", skip_serializing_if = "Option::is_none")]
    pub allow_host_certificates: Option<bool>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If set, host certificates that are requested are allowed to use subdomains of those listed in \"allowed_domains\".
    #[serde(rename = "allow_subdomains", skip_serializing_if = "Option::is_none")]
    pub allow_subdomains: Option<bool>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If set, certificates are allowed to be signed for use as a 'user'.
    #[serde(rename = "allow_user_certificates", skip_serializing_if = "Option::is_none")]
    pub allow_user_certificates: Option<bool>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If true, users can override the key ID for a signed certificate with the \"key_id\" field. When false, the key ID will always be the token display name. The key ID is logged by the SSH server and can be useful for auditing.
    #[serde(rename = "allow_user_key_ids", skip_serializing_if = "Option::is_none")]
    pub allow_user_key_ids: Option<bool>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] A comma-separated list of critical options that certificates can have when signed. To allow any critical options, set this to an empty string.
    #[serde(rename = "allowed_critical_options", skip_serializing_if = "Option::is_none")]
    pub allowed_critical_options: Option<String>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If this option is not specified, client can request for a signed certificate for any valid host. If only certain domains are allowed, then this list enforces it.
    #[serde(rename = "allowed_domains", skip_serializing_if = "Option::is_none")]
    pub allowed_domains: Option<String>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] A comma-separated list of extensions that certificates can have when signed. To allow any extensions, set this to an empty string.
    #[serde(rename = "allowed_extensions", skip_serializing_if = "Option::is_none")]
    pub allowed_extensions: Option<String>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If set, allows the enforcement of key types and minimum key sizes to be signed.
    #[serde(rename = "allowed_user_key_lengths", skip_serializing_if = "Option::is_none")]
    pub allowed_user_key_lengths: Option<serde_json::Value>,
    /// [Optional for all types] [Works differently for CA type] If this option is not specified, or is '*', client can request a credential for any valid user at the remote host, including the admin user. If only certain usernames are to be allowed, then this list enforces it. If this field is set, then credentials can only be created for default_user and usernames present in this list. Setting this option will enable all the users with access to this role to fetch credentials for all other usernames in this list. Use with caution. N.B.: with the CA type, an empty list means that no users are allowed; explicitly specify '*' to allow any user.
    #[serde(rename = "allowed_users", skip_serializing_if = "Option::is_none")]
    pub allowed_users: Option<String>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] If set, Allowed users can be specified using identity template policies. Non-templated users are also permitted.
    #[serde(rename = "allowed_users_template", skip_serializing_if = "Option::is_none")]
    pub allowed_users_template: Option<bool>,
    /// [Optional for Dynamic type] [Optional for OTP type] [Not applicable for CA type] Comma separated list of CIDR blocks for which the role is applicable for. CIDR blocks can belong to more than one role.
    #[serde(rename = "cidr_list", skip_serializing_if = "Option::is_none")]
    pub cidr_list: Option<String>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] Critical options certificates should have if none are provided when signing. This field takes in key value pairs in JSON format. Note that these are not restricted by \"allowed_critical_options\". Defaults to none.
    #[serde(rename = "default_critical_options", skip_serializing_if = "Option::is_none")]
    pub default_critical_options: Option<serde_json::Value>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] Extensions certificates should have if none are provided when signing. This field takes in key value pairs in JSON format. Note that these are not restricted by \"allowed_extensions\". Defaults to none.
    #[serde(rename = "default_extensions", skip_serializing_if = "Option::is_none")]
    pub default_extensions: Option<serde_json::Value>,
    /// [Required for Dynamic type] [Required for OTP type] [Optional for CA type] Default username for which a credential will be generated. When the endpoint 'creds/' is used without a username, this value will be used as default username.
    #[serde(rename = "default_user", skip_serializing_if = "Option::is_none")]
    pub default_user: Option<String>,
    /// [Optional for Dynamic type] [Optional for OTP type] [Not applicable for CA type] Comma separated list of CIDR blocks. IP addresses belonging to these blocks are not accepted by the role. This is particularly useful when big CIDR blocks are being used by the role and certain parts of it needs to be kept out.
    #[serde(rename = "exclude_cidr_list", skip_serializing_if = "Option::is_none")]
    pub exclude_cidr_list: Option<String>,
    /// [Optional for Dynamic type] [Not-applicable for OTP type] [Not applicable for CA type] Script used to install and uninstall public keys in the target machine. The inbuilt default install script will be for Linux hosts. For sample script, refer the project documentation website.
    #[serde(rename = "install_script", skip_serializing_if = "Option::is_none")]
    pub install_script: Option<String>,
    /// [Required for Dynamic type] [Not applicable for OTP type] [Not applicable for CA type] Name of the registered key in Vault. Before creating the role, use the 'keys/' endpoint to create a named key.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// [Optional for Dynamic type] [Not applicable for OTP type] [Not applicable for CA type] Length of the RSA dynamic key in bits. It is 1024 by default or it can be 2048.
    #[serde(rename = "key_bits", skip_serializing_if = "Option::is_none")]
    pub key_bits: Option<i32>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] When supplied, this value specifies a custom format for the key id of a signed certificate. The following variables are available for use: '{{token_display_name}}' - The display name of the token used to make the request. '{{role_name}}' - The name of the role signing the request. '{{public_key_hash}}' - A SHA256 checksum of the public key that is being signed.
    #[serde(rename = "key_id_format", skip_serializing_if = "Option::is_none")]
    pub key_id_format: Option<String>,
    /// [Optional for Dynamic type] [Not applicable for OTP type] [Not applicable for CA type] Comma separated option specifications which will be prefixed to RSA key in authorized_keys file. Options should be valid and comply with authorized_keys file format and should not contain spaces.
    #[serde(rename = "key_option_specs", skip_serializing_if = "Option::is_none")]
    pub key_option_specs: Option<String>,
    /// [Required for all types] Type of key used to login to hosts. It can be either 'otp', 'dynamic' or 'ca'. 'otp' type requires agent to be installed in remote hosts.
    #[serde(rename = "key_type", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<KeyType>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] The maximum allowed lease duration
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// [Optional for Dynamic type] [Optional for OTP type] [Not applicable for CA type] Port number for SSH connection. Default is '22'. Port number does not play any role in creation of OTP. For 'otp' type, this is just a way to inform client about the port number to use. Port number will be returned to client by Vault server along with OTP.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// [Not applicable for Dynamic type] [Not applicable for OTP type] [Optional for CA type] The lease duration if no specific lease duration is requested. The lease duration controls the expiration of certificates issued by this backend. Defaults to the value of max_ttl.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl SshRoleInput {
    pub fn new() -> SshRoleInput {
        SshRoleInput {
            admin_user: None,
            algorithm_signer: None,
            allow_bare_domains: None,
            allow_host_certificates: None,
            allow_subdomains: None,
            allow_user_certificates: None,
            allow_user_key_ids: None,
            allowed_critical_options: None,
            allowed_domains: None,
            allowed_extensions: None,
            allowed_user_key_lengths: None,
            allowed_users: None,
            allowed_users_template: None,
            cidr_list: None,
            default_critical_options: None,
            default_extensions: None,
            default_user: None,
            exclude_cidr_list: None,
            install_script: None,
            key: None,
            key_bits: None,
            key_id_format: None,
            key_option_specs: None,
            key_type: None,
            max_ttl: None,
            port: None,
            ttl: None,
        }
    }
}

/// [Required for all types] Type of key used to login to hosts. It can be either 'otp', 'dynamic' or 'ca'. 'otp' type requires agent to be installed in remote hosts.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "otp")]
    Otp,
    #[serde(rename = "dynamic")]
    Dynamic,
    #[serde(rename = "ca")]
    Ca,
}

