/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshConfigCa {
    /// Generate SSH key pair internally rather than use the private_key and public_key fields.
    #[serde(rename = "generate_signing_key", skip_serializing_if = "Option::is_none")]
    pub generate_signing_key: Option<bool>,
    /// Private half of the SSH key that will be used to sign certificates.
    #[serde(rename = "private_key", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<String>,
    /// Public half of the SSH key that will be used to sign certificates.
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
}

impl SshConfigCa {
    pub fn new() -> SshConfigCa {
        SshConfigCa {
            generate_signing_key: None,
            private_key: None,
            public_key: None,
        }
    }
}


