/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshVerifyInput {
    /// [Required] One-Time-Key that needs to be validated
    #[serde(rename = "otp", skip_serializing_if = "Option::is_none")]
    pub otp: Option<String>,
}

impl SshVerifyInput {
    pub fn new() -> SshVerifyInput {
        SshVerifyInput {
            otp: None,
        }
    }
}


