/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerraformConfigInput {
    /// The address to access Terraform Cloud or Enterprise. Default is \"https://app.terraform.io\".
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// The base path for the Terraform Cloud or Enterprise API. Default is \"/api/v2/\".
    #[serde(rename = "base_path", skip_serializing_if = "Option::is_none")]
    pub base_path: Option<String>,
    /// The token to access Terraform Cloud
    #[serde(rename = "token")]
    pub token: String,
}

impl TerraformConfigInput {
    pub fn new(token: String) -> TerraformConfigInput {
        TerraformConfigInput {
            address: None,
            base_path: None,
            token,
        }
    }
}


