/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotpKeyInput {
    /// The name of the account associated with the key. Required if generate is true.
    #[serde(rename = "account_name", skip_serializing_if = "Option::is_none")]
    pub account_name: Option<String>,
    /// The hashing algorithm used to generate the TOTP token. Options include SHA1, SHA256 and SHA512.
    #[serde(rename = "algorithm", skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<String>,
    /// The number of digits in the generated TOTP token. This value can either be 6 or 8.
    #[serde(rename = "digits", skip_serializing_if = "Option::is_none")]
    pub digits: Option<i32>,
    /// Determines if a QR code and url are returned upon generating a key. Only used if generate is true.
    #[serde(rename = "exported", skip_serializing_if = "Option::is_none")]
    pub exported: Option<bool>,
    /// Determines if a key should be generated by Vault or if a key is being passed from another service.
    #[serde(rename = "generate", skip_serializing_if = "Option::is_none")]
    pub generate: Option<bool>,
    /// The name of the key's issuing organization. Required if generate is true.
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    /// The shared master key used to generate a TOTP token. Only used if generate is false.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Determines the size in bytes of the generated key. Only used if generate is true.
    #[serde(rename = "key_size", skip_serializing_if = "Option::is_none")]
    pub key_size: Option<i32>,
    /// The length of time used to generate a counter for the TOTP token calculation.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// The pixel size of the generated square QR code. Only used if generate is true and exported is true. If this value is 0, a QR code will not be returned.
    #[serde(rename = "qr_size", skip_serializing_if = "Option::is_none")]
    pub qr_size: Option<i32>,
    /// The number of delay periods that are allowed when validating a TOTP token. This value can either be 0 or 1. Only used if generate is true.
    #[serde(rename = "skew", skip_serializing_if = "Option::is_none")]
    pub skew: Option<i32>,
    /// A TOTP url string containing all of the parameters for key setup. Only used if generate is false.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl TotpKeyInput {
    pub fn new() -> TotpKeyInput {
        TotpKeyInput {
            account_name: None,
            algorithm: None,
            digits: None,
            exported: None,
            generate: None,
            issuer: None,
            key: None,
            key_size: None,
            period: None,
            qr_size: None,
            skew: None,
            url: None,
        }
    }
}


