/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransitVerifyInput {
    /// Deprecated: use \"hash_algorithm\" instead.
    #[serde(rename = "algorithm", skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<String>,
    /// Base64 encoded context for key derivation. Required if key derivation is enabled; currently only available with ed25519 keys.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// Hash algorithm to use (POST body parameter). Valid values are: * sha1 * sha2-224 * sha2-256 * sha2-384 * sha2-512 Defaults to \"sha2-256\". Not valid for all key types.
    #[serde(rename = "hash_algorithm", skip_serializing_if = "Option::is_none")]
    pub hash_algorithm: Option<String>,
    /// The HMAC, including vault header/key version
    #[serde(rename = "hmac", skip_serializing_if = "Option::is_none")]
    pub hmac: Option<String>,
    /// The base64-encoded input data to verify
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<String>,
    /// The method by which to unmarshal the signature when verifying. The default is 'asn1' which is used by openssl and X.509; can also be set to 'jws' which is used for JWT signatures in which case the signature is also expected to be url-safe base64 encoding instead of standard base64 encoding. Currently only valid for ECDSA P-256 key types\".
    #[serde(rename = "marshaling_algorithm", skip_serializing_if = "Option::is_none")]
    pub marshaling_algorithm: Option<String>,
    /// Set to 'true' when the input is already hashed. If the key type is 'rsa-2048', 'rsa-3072' or 'rsa-4096', then the algorithm used to hash the input should be indicated by the 'algorithm' parameter.
    #[serde(rename = "prehashed", skip_serializing_if = "Option::is_none")]
    pub prehashed: Option<bool>,
    /// The signature, including vault header/key version
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    /// The signature algorithm to use for signature verification. Currently only applies to RSA key types. Options are 'pss' or 'pkcs1v15'. Defaults to 'pss'
    #[serde(rename = "signature_algorithm", skip_serializing_if = "Option::is_none")]
    pub signature_algorithm: Option<String>,
    /// Hash algorithm to use (POST URL parameter)
    #[serde(rename = "urlalgorithm", skip_serializing_if = "Option::is_none")]
    pub urlalgorithm: Option<String>,
}

impl TransitVerifyInput {
    pub fn new() -> TransitVerifyInput {
        TransitVerifyInput {
            algorithm: None,
            context: None,
            hash_algorithm: None,
            hmac: None,
            input: None,
            marshaling_algorithm: None,
            prehashed: None,
            signature: None,
            signature_algorithm: None,
            urlalgorithm: None,
        }
    }
}


