/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransitKeyConfigInput {
    /// Enables taking a backup of the named key in plaintext format. Once set, this cannot be disabled.
    #[serde(rename = "allow_plaintext_backup", skip_serializing_if = "Option::is_none")]
    pub allow_plaintext_backup: Option<bool>,
    /// Whether to allow deletion of the key
    #[serde(rename = "deletion_allowed", skip_serializing_if = "Option::is_none")]
    pub deletion_allowed: Option<bool>,
    /// Enables export of the key. Once set, this cannot be disabled.
    #[serde(rename = "exportable", skip_serializing_if = "Option::is_none")]
    pub exportable: Option<bool>,
    /// If set, the minimum version of the key allowed to be decrypted. For signing keys, the minimum version allowed to be used for verification.
    #[serde(rename = "min_decryption_version", skip_serializing_if = "Option::is_none")]
    pub min_decryption_version: Option<i32>,
    /// If set, the minimum version of the key allowed to be used for encryption; or for signing keys, to be used for signing. If set to zero, only the latest version of the key is allowed.
    #[serde(rename = "min_encryption_version", skip_serializing_if = "Option::is_none")]
    pub min_encryption_version: Option<i32>,
}

impl TransitKeyConfigInput {
    pub fn new() -> TransitKeyConfigInput {
        TransitKeyConfigInput {
            allow_plaintext_backup: None,
            deletion_allowed: None,
            exportable: None,
            min_decryption_version: None,
            min_encryption_version: None,
        }
    }
}


