/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransitKeyTrimInput {
    /// The minimum available version for the key ring. All versions before this version will be permanently deleted. This value can at most be equal to the lesser of 'min_decryption_version' and 'min_encryption_version'. This is not allowed to be set when either 'min_encryption_version' or 'min_decryption_version' is set to zero.
    #[serde(rename = "min_available_version", skip_serializing_if = "Option::is_none")]
    pub min_available_version: Option<i32>,
}

impl TransitKeyTrimInput {
    pub fn new() -> TransitKeyTrimInput {
        TransitKeyTrimInput {
            min_available_version: None,
        }
    }
}


