/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject182 {
    /// The versions to destroy. Their data will be permanently deleted.
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<i32>>,
}

impl InlineObject182 {
    pub fn new() -> InlineObject182 {
        InlineObject182 {
            versions: None,
        }
    }
}


