/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject216 {
    /// The args passed to plugin command.
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
    /// The command used to start the plugin. The executable defined in this command must exist in vault's plugin directory.
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// The environment variables passed to plugin command. Each entry is of the form \"key=value\".
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<String>>,
    /// The SHA256 sum of the executable used in the command field. This should be HEX encoded.
    #[serde(rename = "sha256", skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
    /// The SHA256 sum of the executable used in the command field. This should be HEX encoded.
    #[serde(rename = "sha_256", skip_serializing_if = "Option::is_none")]
    pub sha_256: Option<String>,
    /// The type of the plugin, may be auth, secret, or database
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl InlineObject216 {
    pub fn new() -> InlineObject216 {
        InlineObject216 {
            args: None,
            command: None,
            env: None,
            sha256: None,
            sha_256: None,
            _type: None,
        }
    }
}


