/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject46 {
    /// The public certificate that should be trusted. May be DER or PEM encoded. Note: the expiration time is ignored; if the CRL is no longer valid, delete it using the same name as specified here.
    #[serde(rename = "crl", skip_serializing_if = "Option::is_none")]
    pub crl: Option<String>,
}

impl InlineObject46 {
    pub fn new() -> InlineObject46 {
        InlineObject46 {
            crl: None,
        }
    }
}


