/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject200 {
    #[serde(rename = "hmac", skip_serializing_if = "Option::is_none")]
    pub hmac: Option<bool>,
}

impl InlineObject200 {
    pub fn new() -> InlineObject200 {
        InlineObject200 {
            hmac: None,
        }
    }
}


