/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject8 {
    /// The request headers. This must include the headers over which AliCloud has included a signature.
    #[serde(rename = "identity_request_headers", skip_serializing_if = "Option::is_none")]
    pub identity_request_headers: Option<String>,
    /// Base64-encoded full URL against which to make the AliCloud request.
    #[serde(rename = "identity_request_url", skip_serializing_if = "Option::is_none")]
    pub identity_request_url: Option<String>,
    /// Name of the role against which the login is being attempted. If 'role' is not specified, then the login endpoint looks for a role name in the ARN returned by the GetCallerIdentity request. If a matching role is not found, login fails.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
}

impl InlineObject8 {
    pub fn new() -> InlineObject8 {
        InlineObject8 {
            identity_request_headers: None,
            identity_request_url: None,
            role: None,
        }
    }
}


