/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject98 {
    /// Accessor of the token to renew (request body)
    #[serde(rename = "accessor", skip_serializing_if = "Option::is_none")]
    pub accessor: Option<String>,
    /// The desired increment in seconds to the token expiration
    #[serde(rename = "increment", skip_serializing_if = "Option::is_none")]
    pub increment: Option<i32>,
}

impl InlineObject98 {
    pub fn new() -> InlineObject98 {
        InlineObject98 {
            accessor: None,
            increment: None,
        }
    }
}


