/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject158 {
    /// Nomad server address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// CA certificate to use when verifying Nomad server certificate, must be x509 PEM encoded.
    #[serde(rename = "ca_cert", skip_serializing_if = "Option::is_none")]
    pub ca_cert: Option<String>,
    /// Client certificate used for Nomad's TLS communication, must be x509 PEM encoded and if this is set you need to also set client_key.
    #[serde(rename = "client_cert", skip_serializing_if = "Option::is_none")]
    pub client_cert: Option<String>,
    /// Client key used for Nomad's TLS communication, must be x509 PEM encoded and if this is set you need to also set client_cert.
    #[serde(rename = "client_key", skip_serializing_if = "Option::is_none")]
    pub client_key: Option<String>,
    /// Max length for name of generated Nomad tokens
    #[serde(rename = "max_token_name_length", skip_serializing_if = "Option::is_none")]
    pub max_token_name_length: Option<i32>,
    /// Token for API calls
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl InlineObject158 {
    pub fn new() -> InlineObject158 {
        InlineObject158 {
            address: None,
            ca_cert: None,
            client_cert: None,
            client_key: None,
            max_token_name_length: None,
            token: None,
        }
    }
}


