/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject128 {
    /// Optional base64-encoded data that, if specified, must also be provided to decrypt this payload.
    #[serde(rename = "additional_authenticated_data", skip_serializing_if = "Option::is_none")]
    pub additional_authenticated_data: Option<String>,
    /// Integer version of the crypto key version to use for encryption. If unspecified, this defaults to the latest active crypto key version.
    #[serde(rename = "key_version", skip_serializing_if = "Option::is_none")]
    pub key_version: Option<i32>,
    /// Plaintext value to be encrypted. This can be a string or binary, but the size is limited. See the Google Cloud KMS documentation for information on size limitations by key types.
    #[serde(rename = "plaintext", skip_serializing_if = "Option::is_none")]
    pub plaintext: Option<String>,
}

impl InlineObject128 {
    pub fn new() -> InlineObject128 {
        InlineObject128 {
            additional_authenticated_data: None,
            key_version: None,
            plaintext: None,
        }
    }
}


