/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject245 {
    /// Size of cache, use 0 for an unlimited cache size, defaults to 0
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl InlineObject245 {
    pub fn new() -> InlineObject245 {
        InlineObject245 {
            size: None,
        }
    }
}


