/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject247 {
    /// The ciphertext to decrypt, provided as returned by encrypt.
    #[serde(rename = "ciphertext", skip_serializing_if = "Option::is_none")]
    pub ciphertext: Option<String>,
    /// Base64 encoded context for key derivation. Required if key derivation is enabled.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// Base64 encoded nonce value used during encryption. Must be provided if convergent encryption is enabled for this key and the key was generated with Vault 0.6.1. Not required for keys created in 0.6.2+.
    #[serde(rename = "nonce", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
}

impl InlineObject247 {
    pub fn new() -> InlineObject247 {
        InlineObject247 {
            ciphertext: None,
            context: None,
            nonce: None,
        }
    }
}


