/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject149 {
    /// ID of the alias.
    #[serde(rename = "alias_id", skip_serializing_if = "Option::is_none")]
    pub alias_id: Option<String>,
    /// Accessor of the mount to which the alias belongs to. This should be supplied in conjunction with 'alias_name'.
    #[serde(rename = "alias_mount_accessor", skip_serializing_if = "Option::is_none")]
    pub alias_mount_accessor: Option<String>,
    /// Name of the alias. This should be supplied in conjunction with 'alias_mount_accessor'.
    #[serde(rename = "alias_name", skip_serializing_if = "Option::is_none")]
    pub alias_name: Option<String>,
    /// ID of the entity.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the entity.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl InlineObject149 {
    pub fn new() -> InlineObject149 {
        InlineObject149 {
            alias_id: None,
            alias_mount_accessor: None,
            alias_name: None,
            id: None,
            name: None,
        }
    }
}


