/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject48 {
    /// Google credentials JSON that Vault will use to verify users against GCP APIs. If not specified, will use application default credentials
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<String>,
    /// Indicates what value to use when generating an alias for GCE authentications.
    #[serde(rename = "gce_alias", skip_serializing_if = "Option::is_none")]
    pub gce_alias: Option<String>,
    /// The metadata to include on the aliases and audit logs generated by this plugin. When set to 'default', includes: instance_creation_timestamp, instance_id, instance_name, project_id, project_number, role, service_account_id, service_account_email, zone. Not editing this field means the 'default' fields are included. Explicitly setting this field to empty overrides the 'default' and means no metadata will be included. If not using 'default', explicit fields must be sent like: 'field1,field2'.
    #[serde(rename = "gce_metadata", skip_serializing_if = "Option::is_none")]
    pub gce_metadata: Option<Vec<String>>,
    /// Deprecated. This field does nothing and be removed in a future release
    #[serde(rename = "google_certs_endpoint", skip_serializing_if = "Option::is_none")]
    pub google_certs_endpoint: Option<String>,
    /// Indicates what value to use when generating an alias for IAM authentications.
    #[serde(rename = "iam_alias", skip_serializing_if = "Option::is_none")]
    pub iam_alias: Option<String>,
    /// The metadata to include on the aliases and audit logs generated by this plugin. When set to 'default', includes: project_id, role, service_account_id, service_account_email. Not editing this field means the 'default' fields are included. Explicitly setting this field to empty overrides the 'default' and means no metadata will be included. If not using 'default', explicit fields must be sent like: 'field1,field2'.
    #[serde(rename = "iam_metadata", skip_serializing_if = "Option::is_none")]
    pub iam_metadata: Option<Vec<String>>,
}

impl InlineObject48 {
    pub fn new() -> InlineObject48 {
        InlineObject48 {
            credentials: None,
            gce_alias: None,
            gce_metadata: None,
            google_certs_endpoint: None,
            iam_alias: None,
            iam_metadata: None,
        }
    }
}


