/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject17 {
    /// Identifier of the role. Defaults to a UUID.
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<String>,
}

impl InlineObject17 {
    pub fn new() -> InlineObject17 {
        InlineObject17 {
            role_id: None,
        }
    }
}


