/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject154 {
    /// Controls how long the public portion of a key will be available for verification after being rotated. Setting verification_ttl here will override the verification_ttl set on the key.
    #[serde(rename = "verification_ttl", skip_serializing_if = "Option::is_none")]
    pub verification_ttl: Option<i32>,
}

impl InlineObject154 {
    pub fn new() -> InlineObject154 {
        InlineObject154 {
            verification_ttl: None,
        }
    }
}


