/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject60 {
    /// The value against which to match the 'iss' claim in a JWT. Optional.
    #[serde(rename = "bound_issuer", skip_serializing_if = "Option::is_none")]
    pub bound_issuer: Option<String>,
    /// The default role to use if none is provided during login. If not set, a role is required during login.
    #[serde(rename = "default_role", skip_serializing_if = "Option::is_none")]
    pub default_role: Option<String>,
    /// The CA certificate or chain of certificates, in PEM format, to use to validate connections to the JWKS URL. If not set, system certificates are used.
    #[serde(rename = "jwks_ca_pem", skip_serializing_if = "Option::is_none")]
    pub jwks_ca_pem: Option<String>,
    /// JWKS URL to use to authenticate signatures. Cannot be used with \"oidc_discovery_url\" or \"jwt_validation_pubkeys\".
    #[serde(rename = "jwks_url", skip_serializing_if = "Option::is_none")]
    pub jwks_url: Option<String>,
    /// A list of supported signing algorithms. Defaults to RS256.
    #[serde(rename = "jwt_supported_algs", skip_serializing_if = "Option::is_none")]
    pub jwt_supported_algs: Option<Vec<String>>,
    /// A list of PEM-encoded public keys to use to authenticate signatures locally. Cannot be used with \"jwks_url\" or \"oidc_discovery_url\".
    #[serde(rename = "jwt_validation_pubkeys", skip_serializing_if = "Option::is_none")]
    pub jwt_validation_pubkeys: Option<Vec<String>>,
    /// Pass namespace in the OIDC state parameter instead of as a separate query parameter. With this setting, the allowed redirect URL(s) in Vault and on the provider side should not contain a namespace query parameter. This means only one redirect URL entry needs to be maintained on the provider side for all vault namespaces that will be authenticating against it. Defaults to true for new configs.
    #[serde(rename = "namespace_in_state", skip_serializing_if = "Option::is_none")]
    pub namespace_in_state: Option<bool>,
    /// The OAuth Client ID configured with your OIDC provider.
    #[serde(rename = "oidc_client_id", skip_serializing_if = "Option::is_none")]
    pub oidc_client_id: Option<String>,
    /// The OAuth Client Secret configured with your OIDC provider.
    #[serde(rename = "oidc_client_secret", skip_serializing_if = "Option::is_none")]
    pub oidc_client_secret: Option<String>,
    /// The CA certificate or chain of certificates, in PEM format, to use to validate connections to the OIDC Discovery URL. If not set, system certificates are used.
    #[serde(rename = "oidc_discovery_ca_pem", skip_serializing_if = "Option::is_none")]
    pub oidc_discovery_ca_pem: Option<String>,
    /// OIDC Discovery URL, without any .well-known component (base path). Cannot be used with \"jwks_url\" or \"jwt_validation_pubkeys\".
    #[serde(rename = "oidc_discovery_url", skip_serializing_if = "Option::is_none")]
    pub oidc_discovery_url: Option<String>,
    /// The response mode to be used in the OAuth2 request. Allowed values are 'query' and 'form_post'.
    #[serde(rename = "oidc_response_mode", skip_serializing_if = "Option::is_none")]
    pub oidc_response_mode: Option<String>,
    /// The response types to request. Allowed values are 'code' and 'id_token'. Defaults to 'code'.
    #[serde(rename = "oidc_response_types", skip_serializing_if = "Option::is_none")]
    pub oidc_response_types: Option<Vec<String>>,
    /// Provider-specific configuration. Optional.
    #[serde(rename = "provider_config", skip_serializing_if = "Option::is_none")]
    pub provider_config: Option<serde_json::Value>,
}

impl InlineObject60 {
    pub fn new() -> InlineObject60 {
        InlineObject60 {
            bound_issuer: None,
            default_role: None,
            jwks_ca_pem: None,
            jwks_url: None,
            jwt_supported_algs: None,
            jwt_validation_pubkeys: None,
            namespace_in_state: None,
            oidc_client_id: None,
            oidc_client_secret: None,
            oidc_discovery_ca_pem: None,
            oidc_discovery_url: None,
            oidc_response_mode: None,
            oidc_response_types: None,
            provider_config: None,
        }
    }
}


