/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject136 {
    /// Entity ID to which this alias should be tied to
    #[serde(rename = "canonical_id", skip_serializing_if = "Option::is_none")]
    pub canonical_id: Option<String>,
    /// Entity ID to which this alias should be tied to. This field is deprecated in favor of 'canonical_id'.
    #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    /// Mount accessor to which this alias belongs to
    #[serde(rename = "mount_accessor", skip_serializing_if = "Option::is_none")]
    pub mount_accessor: Option<String>,
    /// Name of the alias
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl InlineObject136 {
    pub fn new() -> InlineObject136 {
        InlineObject136 {
            canonical_id: None,
            entity_id: None,
            mount_accessor: None,
            name: None,
        }
    }
}


