/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject51 {
    /// BoundLabels to add (in $key:$value)
    #[serde(rename = "add", skip_serializing_if = "Option::is_none")]
    pub add: Option<Vec<String>>,
    /// Label key values to remove
    #[serde(rename = "remove", skip_serializing_if = "Option::is_none")]
    pub remove: Option<Vec<String>>,
}

impl InlineObject51 {
    pub fn new() -> InlineObject51 {
        InlineObject51 {
            add: None,
            remove: None,
        }
    }
}


