/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject40 {
    /// The amount of extra time that must have passed beyond the roletag expiration, before it is removed from the backend storage.
    #[serde(rename = "safety_buffer", skip_serializing_if = "Option::is_none")]
    pub safety_buffer: Option<i32>,
}

impl InlineObject40 {
    pub fn new() -> InlineObject40 {
        InlineObject40 {
            safety_buffer: None,
        }
    }
}


