/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject18 {
    /// Comma separated string or list of CIDR blocks enforcing secret IDs to be used from specific set of IP addresses. If 'bound_cidr_list' is set on the role, then the list of CIDR blocks listed here should be a subset of the CIDR blocks listed on the role.
    #[serde(rename = "cidr_list", skip_serializing_if = "Option::is_none")]
    pub cidr_list: Option<Vec<String>>,
    /// Metadata to be tied to the SecretID. This should be a JSON formatted string containing the metadata in key value pairs.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
}

impl InlineObject18 {
    pub fn new() -> InlineObject18 {
        InlineObject18 {
            cidr_list: None,
            metadata: None,
            token_bound_cidrs: None,
        }
    }
}


