/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject11 {
    /// Impose secret_id to be presented when logging in using this role. Defaults to 'true'.
    #[serde(rename = "bind_secret_id", skip_serializing_if = "Option::is_none")]
    pub bind_secret_id: Option<bool>,
    /// Use \"secret_id_bound_cidrs\" instead.
    #[serde(rename = "bound_cidr_list", skip_serializing_if = "Option::is_none")]
    pub bound_cidr_list: Option<Vec<String>>,
    /// If set, the secret IDs generated using this role will be cluster local. This can only be set during role creation and once set, it can't be reset later.
    #[serde(rename = "local_secret_ids", skip_serializing_if = "Option::is_none")]
    pub local_secret_ids: Option<bool>,
    /// Use \"token_period\" instead. If this and \"token_period\" are both specified, only \"token_period\" will be used.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// Use \"token_policies\" instead. If this and \"token_policies\" are both specified, only \"token_policies\" will be used.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// Identifier of the role. Defaults to a UUID.
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<String>,
    /// Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can perform the login operation.
    #[serde(rename = "secret_id_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub secret_id_bound_cidrs: Option<Vec<String>>,
    /// Number of times a SecretID can access the role, after which the SecretID will expire. Defaults to 0 meaning that the the secret_id is of unlimited use.
    #[serde(rename = "secret_id_num_uses", skip_serializing_if = "Option::is_none")]
    pub secret_id_num_uses: Option<i32>,
    /// Duration in seconds after which the issued SecretID should expire. Defaults to 0, meaning no expiration.
    #[serde(rename = "secret_id_ttl", skip_serializing_if = "Option::is_none")]
    pub secret_id_ttl: Option<i32>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// The maximum lifetime of the generated token
    #[serde(rename = "token_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// Comma-separated list of policies
    #[serde(rename = "token_policies", skip_serializing_if = "Option::is_none")]
    pub token_policies: Option<Vec<String>>,
    /// The initial ttl of the token to generate
    #[serde(rename = "token_ttl", skip_serializing_if = "Option::is_none")]
    pub token_ttl: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
}

impl InlineObject11 {
    pub fn new() -> InlineObject11 {
        InlineObject11 {
            bind_secret_id: None,
            bound_cidr_list: None,
            local_secret_ids: None,
            period: None,
            policies: None,
            role_id: None,
            secret_id_bound_cidrs: None,
            secret_id_num_uses: None,
            secret_id_ttl: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_policies: None,
            token_ttl: None,
            token_type: None,
        }
    }
}


