/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject30 {
    /// Base64 encoded AWS Public cert required to verify PKCS7 signature of the EC2 instance metadata.
    #[serde(rename = "aws_public_cert", skip_serializing_if = "Option::is_none")]
    pub aws_public_cert: Option<String>,
    /// Takes the value of either \"pkcs7\" or \"identity\", indicating the type of document which can be verified using the given certificate. The reason is that the PKCS#7 document will have a DSA digest and the identity signature will have an RSA signature, and accordingly the public certificates to verify those also vary. Defaults to \"pkcs7\".
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl InlineObject30 {
    pub fn new() -> InlineObject30 {
        InlineObject30 {
            aws_public_cert: None,
            _type: None,
        }
    }
}


