/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject259 {
    /// Backed up key data to be restored. This should be the output from the 'backup/' endpoint.
    #[serde(rename = "backup", skip_serializing_if = "Option::is_none")]
    pub backup: Option<String>,
    /// If set and a key by the given name exists, force the restore operation and override the key.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

impl InlineObject259 {
    pub fn new() -> InlineObject259 {
        InlineObject259 {
            backup: None,
            force: None,
        }
    }
}


