/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject221 {
    /// The rules of the policy.
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    /// The rules of the policy.
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<String>,
}

impl InlineObject221 {
    pub fn new() -> InlineObject221 {
        InlineObject221 {
            policy: None,
            rules: None,
        }
    }
}


