/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject133 {
    /// Digest to sign. This digest must use the same SHA algorithm as the underlying Cloud KMS key. The digest must be the base64-encoded binary value. This field is required.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,
    /// Integer version of the crypto key version to use for signing. This field is required.
    #[serde(rename = "key_version", skip_serializing_if = "Option::is_none")]
    pub key_version: Option<i32>,
}

impl InlineObject133 {
    pub fn new() -> InlineObject133 {
        InlineObject133 {
            digest: None,
            key_version: None,
        }
    }
}


