/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject45 {
    /// If set, during renewal, skips the matching of presented client identity with the client identity used during login. Defaults to false.
    #[serde(rename = "disable_binding", skip_serializing_if = "Option::is_none")]
    pub disable_binding: Option<bool>,
}

impl InlineObject45 {
    pub fn new() -> InlineObject45 {
        InlineObject45 {
            disable_binding: None,
        }
    }
}


