/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject249 {
    /// Algorithm to use (POST body parameter). Valid values are: * sha2-224 * sha2-256 * sha2-384 * sha2-512 Defaults to \"sha2-256\".
    #[serde(rename = "algorithm", skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<String>,
    /// Encoding format to use. Can be \"hex\" or \"base64\". Defaults to \"hex\".
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    /// The base64-encoded input data
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<String>,
    /// Algorithm to use (POST URL parameter)
    #[serde(rename = "urlalgorithm", skip_serializing_if = "Option::is_none")]
    pub urlalgorithm: Option<String>,
}

impl InlineObject249 {
    pub fn new() -> InlineObject249 {
        InlineObject249 {
            algorithm: None,
            format: None,
            input: None,
            urlalgorithm: None,
        }
    }
}


