/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject226 {
    /// Specifies if using PGP-encrypted keys, whether Vault should also store a plaintext backup of the PGP-encrypted keys.
    #[serde(rename = "backup", skip_serializing_if = "Option::is_none")]
    pub backup: Option<bool>,
    /// Specifies an array of PGP public keys used to encrypt the output unseal keys. Ordering is preserved. The keys must be base64-encoded from their original binary representation. The size of this array must be the same as secret_shares.
    #[serde(rename = "pgp_keys", skip_serializing_if = "Option::is_none")]
    pub pgp_keys: Option<Vec<String>>,
    /// Turns on verification functionality
    #[serde(rename = "require_verification", skip_serializing_if = "Option::is_none")]
    pub require_verification: Option<bool>,
    /// Specifies the number of shares to split the master key into.
    #[serde(rename = "secret_shares", skip_serializing_if = "Option::is_none")]
    pub secret_shares: Option<i32>,
    /// Specifies the number of shares required to reconstruct the master key. This must be less than or equal secret_shares. If using Vault HSM with auto-unsealing, this value must be the same as secret_shares.
    #[serde(rename = "secret_threshold", skip_serializing_if = "Option::is_none")]
    pub secret_threshold: Option<i32>,
}

impl InlineObject226 {
    pub fn new() -> InlineObject226 {
        InlineObject226 {
            backup: None,
            pgp_keys: None,
            require_verification: None,
            secret_shares: None,
            secret_threshold: None,
        }
    }
}


