/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject38 {
    /// If set, allows migration of the underlying instance where the client resides. This keys off of pendingTime in the metadata document, so essentially, this disables the client nonce check whenever the instance is migrated to a new host and pendingTime is newer than the previously-remembered time. Use with caution.
    #[serde(rename = "allow_instance_migration", skip_serializing_if = "Option::is_none")]
    pub allow_instance_migration: Option<bool>,
    /// If set, only allows a single token to be granted per instance ID. In order to perform a fresh login, the entry in whitelist for the instance ID needs to be cleared using the 'auth/aws-ec2/identity-whitelist/<instance_id>' endpoint.
    #[serde(rename = "disallow_reauthentication", skip_serializing_if = "Option::is_none")]
    pub disallow_reauthentication: Option<bool>,
    /// Instance ID for which this tag is intended for. If set, the created tag can only be used by the instance with the given ID.
    #[serde(rename = "instance_id", skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
    /// If set, specifies the maximum allowed token lifetime.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Policies to be associated with the tag. If set, must be a subset of the role's policies. If set, but set to an empty value, only the 'default' policy will be given to issued tokens.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
}

impl InlineObject38 {
    pub fn new() -> InlineObject38 {
        InlineObject38 {
            allow_instance_migration: None,
            disallow_reauthentication: None,
            instance_id: None,
            max_ttl: None,
            policies: None,
        }
    }
}


