/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject127 {
    /// Optional data that was specified during encryption of this payload.
    #[serde(rename = "additional_authenticated_data", skip_serializing_if = "Option::is_none")]
    pub additional_authenticated_data: Option<String>,
    /// Ciphertext to decrypt as previously returned from an encrypt operation. This must be base64-encoded ciphertext as previously returned from an encrypt operation.
    #[serde(rename = "ciphertext", skip_serializing_if = "Option::is_none")]
    pub ciphertext: Option<String>,
    /// Integer version of the crypto key version to use for decryption. This is required for asymmetric keys. For symmetric keys, Cloud KMS will choose the correct version automatically.
    #[serde(rename = "key_version", skip_serializing_if = "Option::is_none")]
    pub key_version: Option<i32>,
}

impl InlineObject127 {
    pub fn new() -> InlineObject127 {
        InlineObject127 {
            additional_authenticated_data: None,
            ciphertext: None,
            key_version: None,
        }
    }
}


