/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject56 {
    /// Multi-factor auth method to use (optional)
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// One time passcode (optional)
    #[serde(rename = "passcode", skip_serializing_if = "Option::is_none")]
    pub passcode: Option<String>,
    /// GitHub personal API token
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl InlineObject56 {
    pub fn new() -> InlineObject56 {
        InlineObject56 {
            method: None,
            passcode: None,
            token: None,
        }
    }
}


