/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject129 {
    /// Maximum allowed crypto key version. If set to a positive value, key versions greater than the given value are not permitted to be used. If set to 0 or a negative value, there is no maximum key version.
    #[serde(rename = "max_version", skip_serializing_if = "Option::is_none")]
    pub max_version: Option<i32>,
    /// Minimum allowed crypto key version. If set to a positive value, key versions less than the given value are not permitted to be used. If set to 0 or a negative value, there is no minimum key version. This value only affects encryption/re-encryption, not decryption. To restrict old values from being decrypted, increase this value and then perform a trim operation.
    #[serde(rename = "min_version", skip_serializing_if = "Option::is_none")]
    pub min_version: Option<i32>,
}

impl InlineObject129 {
    pub fn new() -> InlineObject129 {
        InlineObject129 {
            max_version: None,
            min_version: None,
        }
    }
}


