/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject174 {
    /// The requested Subject Alternative Names, if any, in a comma-delimited list. If email protection is enabled for the role, this may contain email addresses.
    #[serde(rename = "alt_names", skip_serializing_if = "Option::is_none")]
    pub alt_names: Option<String>,
    /// The requested common name; if you want more than one, specify the alternative names in the alt_names map. If email protection is enabled in the role, this may be an email address.
    #[serde(rename = "common_name", skip_serializing_if = "Option::is_none")]
    pub common_name: Option<String>,
    /// PEM-format CSR to be signed.
    #[serde(rename = "csr", skip_serializing_if = "Option::is_none")]
    pub csr: Option<String>,
    /// If true, the Common Name will not be included in DNS or Email Subject Alternate Names. Defaults to false (CN is included).
    #[serde(rename = "exclude_cn_from_sans", skip_serializing_if = "Option::is_none")]
    pub exclude_cn_from_sans: Option<bool>,
    /// Format for returned data. Can be \"pem\", \"der\", or \"pem_bundle\". If \"pem_bundle\" any private key and issuing cert will be appended to the certificate pem. Defaults to \"pem\".
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// The requested IP SANs, if any, in a comma-delimited list
    #[serde(rename = "ip_sans", skip_serializing_if = "Option::is_none")]
    pub ip_sans: Option<Vec<String>>,
    /// Requested other SANs, in an array with the format <oid>;UTF8:<utf8 string value> for each entry.
    #[serde(rename = "other_sans", skip_serializing_if = "Option::is_none")]
    pub other_sans: Option<Vec<String>>,
    /// Format for the returned private key. Generally the default will be controlled by the \"format\" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to \"pkcs8\" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to \"der\".
    #[serde(rename = "private_key_format", skip_serializing_if = "Option::is_none")]
    pub private_key_format: Option<PrivateKeyFormat>,
    /// The requested serial number, if any. If you want more than one, specify alternative names in the alt_names map using OID 2.5.4.5.
    #[serde(rename = "serial_number", skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    /// The requested Time To Live for the certificate; sets the expiration date. If not specified the role default, backend default, or system default TTL is used, in that order. Cannot be larger than the role max TTL.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// The requested URI SANs, if any, in a comma-delimited list.
    #[serde(rename = "uri_sans", skip_serializing_if = "Option::is_none")]
    pub uri_sans: Option<Vec<String>>,
}

impl InlineObject174 {
    pub fn new() -> InlineObject174 {
        InlineObject174 {
            alt_names: None,
            common_name: None,
            csr: None,
            exclude_cn_from_sans: None,
            format: None,
            ip_sans: None,
            other_sans: None,
            private_key_format: None,
            serial_number: None,
            ttl: None,
            uri_sans: None,
        }
    }
}

/// Format for returned data. Can be \"pem\", \"der\", or \"pem_bundle\". If \"pem_bundle\" any private key and issuing cert will be appended to the certificate pem. Defaults to \"pem\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "pem")]
    Pem,
    #[serde(rename = "der")]
    Der,
    #[serde(rename = "pem_bundle")]
    PemBundle,
}
/// Format for the returned private key. Generally the default will be controlled by the \"format\" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to \"pkcs8\" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to \"der\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrivateKeyFormat {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "der")]
    Der,
    #[serde(rename = "pem")]
    Pem,
    #[serde(rename = "pkcs8")]
    Pkcs8,
}

