/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject153 {
    /// Signing algorithm to use. This will default to RS256.
    #[serde(rename = "algorithm", skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<String>,
    /// Comma separated string or array of role client ids allowed to use this key for signing. If empty no roles are allowed. If \"*\" all roles are allowed.
    #[serde(rename = "allowed_client_ids", skip_serializing_if = "Option::is_none")]
    pub allowed_client_ids: Option<Vec<String>>,
    /// How often to generate a new keypair.
    #[serde(rename = "rotation_period", skip_serializing_if = "Option::is_none")]
    pub rotation_period: Option<i32>,
    /// Controls how long the public portion of a key will be available for verification after being rotated.
    #[serde(rename = "verification_ttl", skip_serializing_if = "Option::is_none")]
    pub verification_ttl: Option<i32>,
}

impl InlineObject153 {
    pub fn new() -> InlineObject153 {
        InlineObject153 {
            algorithm: None,
            allowed_client_ids: None,
            rotation_period: None,
            verification_ttl: None,
        }
    }
}


