/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject65 {
    /// Disable JWT issuer validation. Allows to skip ISS validation.
    #[serde(rename = "disable_iss_validation", skip_serializing_if = "Option::is_none")]
    pub disable_iss_validation: Option<bool>,
    /// Disable defaulting to the local CA cert and service account JWT when running in a Kubernetes pod
    #[serde(rename = "disable_local_ca_jwt", skip_serializing_if = "Option::is_none")]
    pub disable_local_ca_jwt: Option<bool>,
    /// Optional JWT issuer. If no issuer is specified, then this plugin will use kubernetes.io/serviceaccount as the default issuer.
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    /// PEM encoded CA cert for use by the TLS client used to talk with the API.
    #[serde(rename = "kubernetes_ca_cert", skip_serializing_if = "Option::is_none")]
    pub kubernetes_ca_cert: Option<String>,
    /// Host must be a host string, a host:port pair, or a URL to the base of the Kubernetes API server.
    #[serde(rename = "kubernetes_host", skip_serializing_if = "Option::is_none")]
    pub kubernetes_host: Option<String>,
    /// Optional list of PEM-formated public keys or certificates used to verify the signatures of kubernetes service account JWTs. If a certificate is given, its public key will be extracted. Not every installation of Kuberentes exposes these keys.
    #[serde(rename = "pem_keys", skip_serializing_if = "Option::is_none")]
    pub pem_keys: Option<Vec<String>>,
    /// A service account JWT used to access the TokenReview API to validate other JWTs during login. If not set the JWT used for login will be used to access the API.
    #[serde(rename = "token_reviewer_jwt", skip_serializing_if = "Option::is_none")]
    pub token_reviewer_jwt: Option<String>,
}

impl InlineObject65 {
    pub fn new() -> InlineObject65 {
        InlineObject65 {
            disable_iss_validation: None,
            disable_local_ca_jwt: None,
            issuer: None,
            kubernetes_ca_cert: None,
            kubernetes_host: None,
            pem_keys: None,
            token_reviewer_jwt: None,
        }
    }
}


