/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject253 {
    /// Enables taking a backup of the named key in plaintext format. Once set, this cannot be disabled.
    #[serde(rename = "allow_plaintext_backup", skip_serializing_if = "Option::is_none")]
    pub allow_plaintext_backup: Option<bool>,
    /// Base64 encoded context for key derivation. When reading a key with key derivation enabled, if the key type supports public keys, this will return the public key for the given context.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// Whether to support convergent encryption. This is only supported when using a key with key derivation enabled and will require all requests to carry both a context and 96-bit (12-byte) nonce. The given nonce will be used in place of a randomly generated nonce. As a result, when the same context and nonce are supplied, the same ciphertext is generated. It is *very important* when using this mode that you ensure that all nonces are unique for a given context. Failing to do so will severely impact the ciphertext's security.
    #[serde(rename = "convergent_encryption", skip_serializing_if = "Option::is_none")]
    pub convergent_encryption: Option<bool>,
    /// Enables key derivation mode. This allows for per-transaction unique keys for encryption operations.
    #[serde(rename = "derived", skip_serializing_if = "Option::is_none")]
    pub derived: Option<bool>,
    /// Enables keys to be exportable. This allows for all the valid keys in the key ring to be exported.
    #[serde(rename = "exportable", skip_serializing_if = "Option::is_none")]
    pub exportable: Option<bool>,
    /// The type of key to create. Currently, \"aes128-gcm96\" (symmetric), \"aes256-gcm96\" (symmetric), \"ecdsa-p256\" (asymmetric), \"ecdsa-p384\" (asymmetric), \"ecdsa-p521\" (asymmetric), \"ed25519\" (asymmetric), \"rsa-2048\" (asymmetric), \"rsa-3072\" (asymmetric), \"rsa-4096\" (asymmetric) are supported. Defaults to \"aes256-gcm96\".
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl InlineObject253 {
    pub fn new() -> InlineObject253 {
        InlineObject253 {
            allow_plaintext_backup: None,
            context: None,
            convergent_encryption: None,
            derived: None,
            exportable: None,
            _type: None,
        }
    }
}


