/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject183 {
    /// If true the key will require the cas parameter to be set on all write requests. If false, the backend’s configuration will be used.
    #[serde(rename = "cas_required", skip_serializing_if = "Option::is_none")]
    pub cas_required: Option<bool>,
    /// The length of time before a version is deleted. If not set, the backend's configured delete_version_after is used. Cannot be greater than the backend's delete_version_after. A zero duration clears the current setting. A negative duration will cause an error.
    #[serde(rename = "delete_version_after", skip_serializing_if = "Option::is_none")]
    pub delete_version_after: Option<i32>,
    /// The number of versions to keep. If not set, the backend’s configured max version is used.
    #[serde(rename = "max_versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<i32>,
}

impl InlineObject183 {
    pub fn new() -> InlineObject183 {
        InlineObject183 {
            cas_required: None,
            delete_version_after: None,
            max_versions: None,
        }
    }
}


