/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject130 {
    /// Full resource ID of the crypto key including the project, location, key ring, and crypto key like \"projects/%s/locations/%s/keyRings/%s/cryptoKeys/%s\". This crypto key must already exist in Google Cloud KMS unless verify is set to \"false\".
    #[serde(rename = "crypto_key", skip_serializing_if = "Option::is_none")]
    pub crypto_key: Option<String>,
    /// Verify that the given Google Cloud KMS crypto key exists and is accessible before creating the storage entry in Vault. Set this to \"false\" if the key will not exist at creation time.
    #[serde(rename = "verify", skip_serializing_if = "Option::is_none")]
    pub verify: Option<bool>,
}

impl InlineObject130 {
    pub fn new() -> InlineObject130 {
        InlineObject130 {
            crypto_key: None,
            verify: None,
        }
    }
}


