/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject163 {
    /// Comma-separated list of URLs to be used for the CRL distribution points attribute
    #[serde(rename = "crl_distribution_points", skip_serializing_if = "Option::is_none")]
    pub crl_distribution_points: Option<Vec<String>>,
    /// Comma-separated list of URLs to be used for the issuing certificate attribute
    #[serde(rename = "issuing_certificates", skip_serializing_if = "Option::is_none")]
    pub issuing_certificates: Option<Vec<String>>,
    /// Comma-separated list of URLs to be used for the OCSP servers attribute
    #[serde(rename = "ocsp_servers", skip_serializing_if = "Option::is_none")]
    pub ocsp_servers: Option<Vec<String>>,
}

impl InlineObject163 {
    pub fn new() -> InlineObject163 {
        InlineObject163 {
            crl_distribution_points: None,
            issuing_certificates: None,
            ocsp_servers: None,
        }
    }
}


