/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject223 {
    /// If set, when a client reaches a rate limit threshold, the client will be prohibited from any further requests until after the 'block_interval' has elapsed.
    #[serde(rename = "block_interval", skip_serializing_if = "Option::is_none")]
    pub block_interval: Option<i32>,
    /// The duration to enforce rate limiting for (default '1s').
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i32>,
    /// Path of the mount or namespace to apply the quota. A blank path configures a global quota. For example namespace1/ adds a quota to a full namespace, namespace1/auth/userpass adds a quota to userpass in namespace1.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// The maximum number of requests in a given interval to be allowed by the quota rule. The 'rate' must be positive.
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<serde_json::Value>,
    /// Type of the quota rule.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl InlineObject223 {
    pub fn new() -> InlineObject223 {
        InlineObject223 {
            block_interval: None,
            interval: None,
            path: None,
            rate: None,
            _type: None,
        }
    }
}


