/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject151 {
    /// Issuer URL to be used in the iss claim of the token. If not set, Vault's app_addr will be used.
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
}

impl InlineObject151 {
    pub fn new() -> InlineObject151 {
        InlineObject151 {
            issuer: None,
        }
    }
}


