/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject21 {
    /// Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can perform the login operation.
    #[serde(rename = "secret_id_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub secret_id_bound_cidrs: Option<Vec<String>>,
}

impl InlineObject21 {
    pub fn new() -> InlineObject21 {
        InlineObject21 {
            secret_id_bound_cidrs: None,
        }
    }
}


