/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject222 {
    /// If set, starts audit logging of requests that get rejected due to rate limit quota rule violations.
    #[serde(rename = "enable_rate_limit_audit_logging", skip_serializing_if = "Option::is_none")]
    pub enable_rate_limit_audit_logging: Option<bool>,
    /// If set, additional rate limit quota HTTP headers will be added to responses.
    #[serde(rename = "enable_rate_limit_response_headers", skip_serializing_if = "Option::is_none")]
    pub enable_rate_limit_response_headers: Option<bool>,
    /// Specifies the list of exempt paths from all rate limit quotas. If empty no paths will be exempt.
    #[serde(rename = "rate_limit_exempt_paths", skip_serializing_if = "Option::is_none")]
    pub rate_limit_exempt_paths: Option<Vec<String>>,
}

impl InlineObject222 {
    pub fn new() -> InlineObject222 {
        InlineObject222 {
            enable_rate_limit_audit_logging: None,
            enable_rate_limit_response_headers: None,
            rate_limit_exempt_paths: None,
        }
    }
}


