/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject95 {
    /// Accessor of the token to look up (request body)
    #[serde(rename = "accessor", skip_serializing_if = "Option::is_none")]
    pub accessor: Option<String>,
}

impl InlineObject95 {
    pub fn new() -> InlineObject95 {
        InlineObject95 {
            accessor: None,
        }
    }
}


