/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject207 {
    /// Number of months to report if no start date specified.
    #[serde(rename = "default_report_months", skip_serializing_if = "Option::is_none")]
    pub default_report_months: Option<i32>,
    /// Enable or disable collection of client count: enable, disable, or default.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<String>,
    /// Number of months of client data to retain. Setting to 0 will clear all existing data.
    #[serde(rename = "retention_months", skip_serializing_if = "Option::is_none")]
    pub retention_months: Option<i32>,
}

impl InlineObject207 {
    pub fn new() -> InlineObject207 {
        InlineObject207 {
            default_report_months: None,
            enabled: None,
            retention_months: None,
        }
    }
}


