/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject195 {
    /// Configuration for this mount, such as plugin_name.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    /// User-friendly description for this credential backend.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Whether to give the mount access to Vault's external entropy.
    #[serde(rename = "external_entropy_access", skip_serializing_if = "Option::is_none")]
    pub external_entropy_access: Option<bool>,
    /// Mark the mount as a local mount, which is not replicated and is unaffected by replication.
    #[serde(rename = "local", skip_serializing_if = "Option::is_none")]
    pub local: Option<bool>,
    /// The options to pass into the backend. Should be a json object with string keys and values.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<serde_json::Value>,
    /// Name of the auth plugin to use based from the name in the plugin catalog.
    #[serde(rename = "plugin_name", skip_serializing_if = "Option::is_none")]
    pub plugin_name: Option<String>,
    /// Whether to turn on seal wrapping for the mount.
    #[serde(rename = "seal_wrap", skip_serializing_if = "Option::is_none")]
    pub seal_wrap: Option<bool>,
    /// The type of the backend. Example: \"userpass\"
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl InlineObject195 {
    pub fn new() -> InlineObject195 {
        InlineObject195 {
            config: None,
            description: None,
            external_entropy_access: None,
            local: None,
            options: None,
            plugin_name: None,
            seal_wrap: None,
            _type: None,
        }
    }
}


