/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject218 {
    /// The mount paths of the plugin backends to reload.
    #[serde(rename = "mounts", skip_serializing_if = "Option::is_none")]
    pub mounts: Option<Vec<String>>,
    /// The name of the plugin to reload, as registered in the plugin catalog.
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<String>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl InlineObject218 {
    pub fn new() -> InlineObject218 {
        InlineObject218 {
            mounts: None,
            plugin: None,
            scope: None,
        }
    }
}


