/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject2 {
    /// Disable the default behavior of requiring that check-ins are performed by the entity that checked them out.
    #[serde(rename = "disable_check_in_enforcement", skip_serializing_if = "Option::is_none")]
    pub disable_check_in_enforcement: Option<bool>,
    /// In seconds, the max amount of time a check-out's renewals should last. Defaults to 24 hours.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// The username/logon name for the service accounts with which this set will be associated.
    #[serde(rename = "service_account_names", skip_serializing_if = "Option::is_none")]
    pub service_account_names: Option<Vec<String>>,
    /// In seconds, the amount of time a check-out should last. Defaults to 24 hours.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl InlineObject2 {
    pub fn new() -> InlineObject2 {
        InlineObject2 {
            disable_check_in_enforcement: None,
            max_ttl: None,
            service_account_names: None,
            ttl: None,
        }
    }
}


