/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject10 {
    /// Unique identifier of the Role. Required to be supplied when the 'bind_secret_id' constraint is set.
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<String>,
    /// SecretID belong to the App role
    #[serde(rename = "secret_id", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<String>,
}

impl InlineObject10 {
    pub fn new() -> InlineObject10 {
        InlineObject10 {
            role_id: None,
            secret_id: None,
        }
    }
}


