/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject19 {
    /// Accessor of the SecretID
    #[serde(rename = "secret_id_accessor", skip_serializing_if = "Option::is_none")]
    pub secret_id_accessor: Option<String>,
}

impl InlineObject19 {
    pub fn new() -> InlineObject19 {
        InlineObject19 {
            secret_id_accessor: None,
        }
    }
}


