/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject201 {
    /// A comma-separated string or array of strings indicating headers that are allowed on cross-origin requests.
    #[serde(rename = "allowed_headers", skip_serializing_if = "Option::is_none")]
    pub allowed_headers: Option<Vec<String>>,
    /// A comma-separated string or array of strings indicating origins that may make cross-origin requests.
    #[serde(rename = "allowed_origins", skip_serializing_if = "Option::is_none")]
    pub allowed_origins: Option<Vec<String>>,
    /// Enables or disables CORS headers on requests.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
}

impl InlineObject201 {
    pub fn new() -> InlineObject201 {
        InlineObject201 {
            allowed_headers: None,
            allowed_origins: None,
            enable: None,
        }
    }
}


