/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject138 {
    /// Entity ID to which this alias belongs
    #[serde(rename = "canonical_id", skip_serializing_if = "Option::is_none")]
    pub canonical_id: Option<String>,
    /// Entity ID to which this alias belongs. This field is deprecated, use canonical_id.
    #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    /// ID of the entity alias. If set, updates the corresponding entity alias.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Mount accessor to which this alias belongs to; unused for a modify
    #[serde(rename = "mount_accessor", skip_serializing_if = "Option::is_none")]
    pub mount_accessor: Option<String>,
    /// Name of the alias; unused for a modify
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl InlineObject138 {
    pub fn new() -> InlineObject138 {
        InlineObject138 {
            canonical_id: None,
            entity_id: None,
            id: None,
            mount_accessor: None,
            name: None,
        }
    }
}


