/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject120 {
    /// Comma separated string or array of the role names allowed to get creds from this database connection. If empty no roles are allowed. If \"*\" all roles are allowed.
    #[serde(rename = "allowed_roles", skip_serializing_if = "Option::is_none")]
    pub allowed_roles: Option<Vec<String>>,
    /// Password policy to use when generating passwords.
    #[serde(rename = "password_policy", skip_serializing_if = "Option::is_none")]
    pub password_policy: Option<String>,
    /// The name of a builtin or previously registered plugin known to vault. This endpoint will create an instance of that plugin type.
    #[serde(rename = "plugin_name", skip_serializing_if = "Option::is_none")]
    pub plugin_name: Option<String>,
    /// Specifies the database statements to be executed to rotate the root user's credentials. See the plugin's API page for more information on support and formatting for this parameter.
    #[serde(rename = "root_rotation_statements", skip_serializing_if = "Option::is_none")]
    pub root_rotation_statements: Option<Vec<String>>,
    /// If true, the connection details are verified by actually connecting to the database. Defaults to true.
    #[serde(rename = "verify_connection", skip_serializing_if = "Option::is_none")]
    pub verify_connection: Option<bool>,
}

impl InlineObject120 {
    pub fn new() -> InlineObject120 {
        InlineObject120 {
            allowed_roles: None,
            password_policy: None,
            plugin_name: None,
            root_rotation_statements: None,
            verify_connection: None,
        }
    }
}


