/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject89 {
    /// A string of URL-encoded key/value pairs that provides additional context about the authentication attempt in the Duo Mobile app
    #[serde(rename = "push_info", skip_serializing_if = "Option::is_none")]
    pub push_info: Option<String>,
    /// User agent to connect to Duo (default \"\")
    #[serde(rename = "user_agent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    /// Format string given auth method username as argument to create Duo username (default '%s')
    #[serde(rename = "username_format", skip_serializing_if = "Option::is_none")]
    pub username_format: Option<String>,
}

impl InlineObject89 {
    pub fn new() -> InlineObject89 {
        InlineObject89 {
            push_info: None,
            user_agent: None,
            username_format: None,
        }
    }
}


