/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject181 {
    /// The versions to be archived. The versioned data will not be deleted, but it will no longer be returned in normal get requests.
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<i32>>,
}

impl InlineObject181 {
    pub fn new() -> InlineObject181 {
        InlineObject181 {
            versions: None,
        }
    }
}


