/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject90 {
    /// Multi-factor auth method to use (optional)
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// One time passcode (optional)
    #[serde(rename = "passcode", skip_serializing_if = "Option::is_none")]
    pub passcode: Option<String>,
    /// Password for this user.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Username to be used for login. (URL parameter)
    #[serde(rename = "urlusername", skip_serializing_if = "Option::is_none")]
    pub urlusername: Option<String>,
    /// Username to be used for login. (POST request body)
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl InlineObject90 {
    pub fn new() -> InlineObject90 {
        InlineObject90 {
            method: None,
            passcode: None,
            password: None,
            urlusername: None,
            username: None,
        }
    }
}


