/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject165 {
    /// PEM-format certificate. This must be a CA certificate with a public key matching the previously-generated key from the generation endpoint.
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
}

impl InlineObject165 {
    pub fn new() -> InlineObject165 {
        InlineObject165 {
            certificate: None,
        }
    }
}


