/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject157 {
    /// Entity ID to which this persona should be tied to
    #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    /// Metadata to be associated with the persona. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: vault <command> <path> metadata=key1=value1 metadata=key2=value2
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// Mount accessor to which this persona belongs to
    #[serde(rename = "mount_accessor", skip_serializing_if = "Option::is_none")]
    pub mount_accessor: Option<String>,
    /// Name of the persona
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl InlineObject157 {
    pub fn new() -> InlineObject157 {
        InlineObject157 {
            entity_id: None,
            metadata: None,
            mount_accessor: None,
            name: None,
        }
    }
}


