/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject239 {
    /// Specifies a single master key share. This is required unless reset is true.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Specifies if previously-provided unseal keys are discarded and the unseal process is reset.
    #[serde(rename = "reset", skip_serializing_if = "Option::is_none")]
    pub reset: Option<bool>,
}

impl InlineObject239 {
    pub fn new() -> InlineObject239 {
        InlineObject239 {
            key: None,
            reset: None,
        }
    }
}


