/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject196 {
    /// A list of headers to whitelist and allow a plugin to set on responses.
    #[serde(rename = "allowed_response_headers", skip_serializing_if = "Option::is_none")]
    pub allowed_response_headers: Option<Vec<String>>,
    /// The list of keys in the request data object that will not be HMAC'ed by audit devices.
    #[serde(rename = "audit_non_hmac_request_keys", skip_serializing_if = "Option::is_none")]
    pub audit_non_hmac_request_keys: Option<Vec<String>>,
    /// The list of keys in the response data object that will not be HMAC'ed by audit devices.
    #[serde(rename = "audit_non_hmac_response_keys", skip_serializing_if = "Option::is_none")]
    pub audit_non_hmac_response_keys: Option<Vec<String>>,
    /// The default lease TTL for this mount.
    #[serde(rename = "default_lease_ttl", skip_serializing_if = "Option::is_none")]
    pub default_lease_ttl: Option<String>,
    /// User-friendly description for this credential backend.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Determines the visibility of the mount in the UI-specific listing endpoint. Accepted value are 'unauth' and ''.
    #[serde(rename = "listing_visibility", skip_serializing_if = "Option::is_none")]
    pub listing_visibility: Option<String>,
    /// The max lease TTL for this mount.
    #[serde(rename = "max_lease_ttl", skip_serializing_if = "Option::is_none")]
    pub max_lease_ttl: Option<String>,
    /// The options to pass into the backend. Should be a json object with string keys and values.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<serde_json::Value>,
    /// A list of headers to whitelist and pass from the request to the plugin.
    #[serde(rename = "passthrough_request_headers", skip_serializing_if = "Option::is_none")]
    pub passthrough_request_headers: Option<Vec<String>>,
    /// The type of token to issue (service or batch).
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
}

impl InlineObject196 {
    pub fn new() -> InlineObject196 {
        InlineObject196 {
            allowed_response_headers: None,
            audit_non_hmac_request_keys: None,
            audit_non_hmac_response_keys: None,
            default_lease_ttl: None,
            description: None,
            listing_visibility: None,
            max_lease_ttl: None,
            options: None,
            passthrough_request_headers: None,
            token_type: None,
        }
    }
}


