/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject36 {
    /// HTTP method to use for the AWS request when auth_type is iam. This must match what has been signed in the presigned request. Currently, POST is the only supported value
    #[serde(rename = "iam_http_request_method", skip_serializing_if = "Option::is_none")]
    pub iam_http_request_method: Option<String>,
    /// Base64-encoded request body when auth_type is iam. This must match the request body included in the signature.
    #[serde(rename = "iam_request_body", skip_serializing_if = "Option::is_none")]
    pub iam_request_body: Option<String>,
    /// Key/value pairs of headers for use in the sts:GetCallerIdentity HTTP requests headers when auth_type is iam. Can be either a Base64-encoded, JSON-serialized string, or a JSON object of key/value pairs. This must at a minimum include the headers over which AWS has included a signature.
    #[serde(rename = "iam_request_headers", skip_serializing_if = "Option::is_none")]
    pub iam_request_headers: Option<String>,
    /// Base64-encoded full URL against which to make the AWS request when using iam auth_type.
    #[serde(rename = "iam_request_url", skip_serializing_if = "Option::is_none")]
    pub iam_request_url: Option<String>,
    /// Base64 encoded EC2 instance identity document. This needs to be supplied along with the 'signature' parameter. If using 'curl' for fetching the identity document, consider using the option '-w 0' while piping the output to 'base64' binary.
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    /// The nonce to be used for subsequent login requests when auth_type is ec2. If this parameter is not specified at all and if reauthentication is allowed, then the backend will generate a random nonce, attaches it to the instance's identity-whitelist entry and returns the nonce back as part of auth metadata. This value should be used with further login requests, to establish client authenticity. Clients can choose to set a custom nonce if preferred, in which case, it is recommended that clients provide a strong nonce. If a nonce is provided but with an empty value, it indicates intent to disable reauthentication. Note that, when 'disallow_reauthentication' option is enabled on either the role or the role tag, the 'nonce' holds no significance.
    #[serde(rename = "nonce", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
    /// PKCS7 signature of the identity document when using an auth_type of ec2.
    #[serde(rename = "pkcs7", skip_serializing_if = "Option::is_none")]
    pub pkcs7: Option<String>,
    /// Name of the role against which the login is being attempted. If 'role' is not specified, then the login endpoint looks for a role bearing the name of the AMI ID of the EC2 instance that is trying to login. If a matching role is not found, login fails.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Base64 encoded SHA256 RSA signature of the instance identity document. This needs to be supplied along with 'identity' parameter.
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl InlineObject36 {
    pub fn new() -> InlineObject36 {
        InlineObject36 {
            iam_http_request_method: None,
            iam_request_body: None,
            iam_request_headers: None,
            iam_request_url: None,
            identity: None,
            nonce: None,
            pkcs7: None,
            role: None,
            signature: None,
        }
    }
}


