/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject37 {
    /// If set, allows migration of the underlying instance where the client resides. This keys off of pendingTime in the metadata document, so essentially, this disables the client nonce check whenever the instance is migrated to a new host and pendingTime is newer than the previously-remembered time. Use with caution. This is only checked when auth_type is ec2.
    #[serde(rename = "allow_instance_migration", skip_serializing_if = "Option::is_none")]
    pub allow_instance_migration: Option<bool>,
    /// The auth_type permitted to authenticate to this role. Must be one of iam or ec2 and cannot be changed after role creation.
    #[serde(rename = "auth_type", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<String>,
    /// If set, defines a constraint on the EC2 instances that the account ID in its identity document to match one of the IDs specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
    #[serde(rename = "bound_account_id", skip_serializing_if = "Option::is_none")]
    pub bound_account_id: Option<Vec<String>>,
    /// If set, defines a constraint on the EC2 instances that they should be using one of the AMI IDs specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
    #[serde(rename = "bound_ami_id", skip_serializing_if = "Option::is_none")]
    pub bound_ami_id: Option<Vec<String>>,
    /// If set, defines a constraint on the EC2 instances to have one of the given instance IDs. Can be a list or comma-separated string of EC2 instance IDs. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
    #[serde(rename = "bound_ec2_instance_id", skip_serializing_if = "Option::is_none")]
    pub bound_ec2_instance_id: Option<Vec<String>>,
    /// If set, defines a constraint on the EC2 instances to be associated with an IAM instance profile ARN which has a prefix that matches one of the values specified by this parameter. The value is prefix-matched (as though it were a glob ending in '*'). This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
    #[serde(rename = "bound_iam_instance_profile_arn", skip_serializing_if = "Option::is_none")]
    pub bound_iam_instance_profile_arn: Option<Vec<String>>,
    /// ARN of the IAM principals to bind to this role. Only applicable when auth_type is iam.
    #[serde(rename = "bound_iam_principal_arn", skip_serializing_if = "Option::is_none")]
    pub bound_iam_principal_arn: Option<Vec<String>>,
    /// If set, defines a constraint on the authenticating EC2 instance that it must match one of the IAM role ARNs specified by this parameter. The value is prefix-matched (as though it were a glob ending in '*'). The configured IAM user or EC2 instance role must be allowed to execute the 'iam:GetInstanceProfile' action if this is specified. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
    #[serde(rename = "bound_iam_role_arn", skip_serializing_if = "Option::is_none")]
    pub bound_iam_role_arn: Option<Vec<String>>,
    /// If set, defines a constraint on the EC2 instances that the region in its identity document match one of the regions specified by this parameter. This is only applicable when auth_type is ec2.
    #[serde(rename = "bound_region", skip_serializing_if = "Option::is_none")]
    pub bound_region: Option<Vec<String>>,
    /// If set, defines a constraint on the EC2 instance to be associated with the subnet ID that matches one of the values specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
    #[serde(rename = "bound_subnet_id", skip_serializing_if = "Option::is_none")]
    pub bound_subnet_id: Option<Vec<String>>,
    /// If set, defines a constraint on the EC2 instance to be associated with a VPC ID that matches one of the value specified by this parameter. This is only applicable when auth_type is ec2 or inferred_entity_type is ec2_instance.
    #[serde(rename = "bound_vpc_id", skip_serializing_if = "Option::is_none")]
    pub bound_vpc_id: Option<Vec<String>>,
    /// If set, only allows a single token to be granted per instance ID. In order to perform a fresh login, the entry in whitelist for the instance ID needs to be cleared using 'auth/aws-ec2/identity-whitelist/<instance_id>' endpoint. This is only applicable when auth_type is ec2.
    #[serde(rename = "disallow_reauthentication", skip_serializing_if = "Option::is_none")]
    pub disallow_reauthentication: Option<bool>,
    /// When auth_type is iam and inferred_entity_type is set, the region to assume the inferred entity exists in.
    #[serde(rename = "inferred_aws_region", skip_serializing_if = "Option::is_none")]
    pub inferred_aws_region: Option<String>,
    /// When auth_type is iam, the AWS entity type to infer from the authenticated principal. The only supported value is ec2_instance, which will extract the EC2 instance ID from the authenticated role and apply the following restrictions specific to EC2 instances: bound_ami_id, bound_account_id, bound_iam_role_arn, bound_iam_instance_profile_arn, bound_vpc_id, bound_subnet_id. The configured EC2 client must be able to find the inferred instance ID in the results, and the instance must be running. If unable to determine the EC2 instance ID or unable to find the EC2 instance ID among running instances, then authentication will fail.
    #[serde(rename = "inferred_entity_type", skip_serializing_if = "Option::is_none")]
    pub inferred_entity_type: Option<String>,
    /// Use \"token_max_ttl\" instead. If this and \"token_max_ttl\" are both specified, only \"token_max_ttl\" will be used.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Use \"token_period\" instead. If this and \"token_period\" are both specified, only \"token_period\" will be used.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// Use \"token_policies\" instead. If this and \"token_policies\" are both specified, only \"token_policies\" will be used.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// If set, resolve all AWS IAM ARNs into AWS's internal unique IDs. When an IAM entity (e.g., user, role, or instance profile) is deleted, then all references to it within the role will be invalidated, which prevents a new IAM entity from being created with the same name and matching the role's IAM binds. Once set, this cannot be unset.
    #[serde(rename = "resolve_aws_unique_ids", skip_serializing_if = "Option::is_none")]
    pub resolve_aws_unique_ids: Option<bool>,
    /// If set, enables the role tags for this role. The value set for this field should be the 'key' of the tag on the EC2 instance. The 'value' of the tag should be generated using 'role/<role>/tag' endpoint. Defaults to an empty string, meaning that role tags are disabled. This is only allowed if auth_type is ec2.
    #[serde(rename = "role_tag", skip_serializing_if = "Option::is_none")]
    pub role_tag: Option<String>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// The maximum lifetime of the generated token
    #[serde(rename = "token_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// Comma-separated list of policies
    #[serde(rename = "token_policies", skip_serializing_if = "Option::is_none")]
    pub token_policies: Option<Vec<String>>,
    /// The initial ttl of the token to generate
    #[serde(rename = "token_ttl", skip_serializing_if = "Option::is_none")]
    pub token_ttl: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    /// Use \"token_ttl\" instead. If this and \"token_ttl\" are both specified, only \"token_ttl\" will be used.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl InlineObject37 {
    pub fn new() -> InlineObject37 {
        InlineObject37 {
            allow_instance_migration: None,
            auth_type: None,
            bound_account_id: None,
            bound_ami_id: None,
            bound_ec2_instance_id: None,
            bound_iam_instance_profile_arn: None,
            bound_iam_principal_arn: None,
            bound_iam_role_arn: None,
            bound_region: None,
            bound_subnet_id: None,
            bound_vpc_id: None,
            disallow_reauthentication: None,
            inferred_aws_region: None,
            inferred_entity_type: None,
            max_ttl: None,
            period: None,
            policies: None,
            resolve_aws_unique_ids: None,
            role_tag: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_policies: None,
            token_ttl: None,
            token_type: None,
            ttl: None,
        }
    }
}


