/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject191 {
    /// Type of certificate to be created; either \"user\" or \"host\".
    #[serde(rename = "cert_type", skip_serializing_if = "Option::is_none")]
    pub cert_type: Option<String>,
    /// Critical options that the certificate should be signed for.
    #[serde(rename = "critical_options", skip_serializing_if = "Option::is_none")]
    pub critical_options: Option<serde_json::Value>,
    /// Extensions that the certificate should be signed for.
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<serde_json::Value>,
    /// Key id that the created certificate should have. If not specified, the display name of the token will be used.
    #[serde(rename = "key_id", skip_serializing_if = "Option::is_none")]
    pub key_id: Option<String>,
    /// SSH public key that should be signed.
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    /// The requested Time To Live for the SSH certificate; sets the expiration date. If not specified the role default, backend default, or system default TTL is used, in that order. Cannot be later than the role max TTL.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// Valid principals, either usernames or hostnames, that the certificate should be signed for.
    #[serde(rename = "valid_principals", skip_serializing_if = "Option::is_none")]
    pub valid_principals: Option<String>,
}

impl InlineObject191 {
    pub fn new() -> InlineObject191 {
        InlineObject191 {
            cert_type: None,
            critical_options: None,
            extensions: None,
            key_id: None,
            public_key: None,
            ttl: None,
            valid_principals: None,
        }
    }
}


