/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject175 {
    /// The amount of extra time that must have passed beyond certificate expiration before it is removed from the backend storage and/or revocation list. Defaults to 72 hours.
    #[serde(rename = "safety_buffer", skip_serializing_if = "Option::is_none")]
    pub safety_buffer: Option<i32>,
    /// Set to true to enable tidying up the certificate store
    #[serde(rename = "tidy_cert_store", skip_serializing_if = "Option::is_none")]
    pub tidy_cert_store: Option<bool>,
    /// Deprecated; synonym for 'tidy_revoked_certs
    #[serde(rename = "tidy_revocation_list", skip_serializing_if = "Option::is_none")]
    pub tidy_revocation_list: Option<bool>,
    /// Set to true to expire all revoked and expired certificates, removing them both from the CRL and from storage. The CRL will be rotated if this causes any values to be removed.
    #[serde(rename = "tidy_revoked_certs", skip_serializing_if = "Option::is_none")]
    pub tidy_revoked_certs: Option<bool>,
}

impl InlineObject175 {
    pub fn new() -> InlineObject175 {
        InlineObject175 {
            safety_buffer: None,
            tidy_cert_store: None,
            tidy_revocation_list: None,
            tidy_revoked_certs: None,
        }
    }
}


