/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject246 {
    /// Number of bits for the key; currently 128, 256, and 512 bits are supported. Defaults to 256.
    #[serde(rename = "bits", skip_serializing_if = "Option::is_none")]
    pub bits: Option<i32>,
    /// Context for key derivation. Required for derived keys.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// The version of the Vault key to use for encryption of the data key. Must be 0 (for latest) or a value greater than or equal to the min_encryption_version configured on the key.
    #[serde(rename = "key_version", skip_serializing_if = "Option::is_none")]
    pub key_version: Option<i32>,
    /// Nonce for when convergent encryption v1 is used (only in Vault 0.6.1)
    #[serde(rename = "nonce", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
}

impl InlineObject246 {
    pub fn new() -> InlineObject246 {
        InlineObject246 {
            bits: None,
            context: None,
            key_version: None,
            nonce: None,
        }
    }
}


