/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject198 {
    /// Accessor of the token for which capabilities are being queried.
    #[serde(rename = "accessor", skip_serializing_if = "Option::is_none")]
    pub accessor: Option<String>,
    /// Use 'paths' instead.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<Vec<String>>,
    /// Paths on which capabilities are being queried.
    #[serde(rename = "paths", skip_serializing_if = "Option::is_none")]
    pub paths: Option<Vec<String>>,
}

impl InlineObject198 {
    pub fn new() -> InlineObject198 {
        InlineObject198 {
            accessor: None,
            path: None,
            paths: None,
        }
    }
}


