/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject164 {
    /// Whether to add a Basic Constraints extension with CA: true. Only needed as a workaround in some compatibility scenarios with Active Directory Certificate Services.
    #[serde(rename = "add_basic_constraints", skip_serializing_if = "Option::is_none")]
    pub add_basic_constraints: Option<bool>,
    /// The requested Subject Alternative Names, if any, in a comma-delimited list. May contain both DNS names and email addresses.
    #[serde(rename = "alt_names", skip_serializing_if = "Option::is_none")]
    pub alt_names: Option<String>,
    /// The requested common name; if you want more than one, specify the alternative names in the alt_names map. If not specified when signing, the common name will be taken from the CSR; other names must still be specified in alt_names or ip_sans.
    #[serde(rename = "common_name", skip_serializing_if = "Option::is_none")]
    pub common_name: Option<String>,
    /// If set, Country will be set to this value.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<Vec<String>>,
    /// If true, the Common Name will not be included in DNS or Email Subject Alternate Names. Defaults to false (CN is included).
    #[serde(rename = "exclude_cn_from_sans", skip_serializing_if = "Option::is_none")]
    pub exclude_cn_from_sans: Option<bool>,
    /// Format for returned data. Can be \"pem\", \"der\", or \"pem_bundle\". If \"pem_bundle\" any private key and issuing cert will be appended to the certificate pem. Defaults to \"pem\".
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// The requested IP SANs, if any, in a comma-delimited list
    #[serde(rename = "ip_sans", skip_serializing_if = "Option::is_none")]
    pub ip_sans: Option<Vec<String>>,
    /// The number of bits to use. You will almost certainly want to change this if you adjust the key_type.
    #[serde(rename = "key_bits", skip_serializing_if = "Option::is_none")]
    pub key_bits: Option<i32>,
    /// The type of key to use; defaults to RSA. \"rsa\" and \"ec\" are the only valid values.
    #[serde(rename = "key_type", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<KeyType>,
    /// If set, Locality will be set to this value.
    #[serde(rename = "locality", skip_serializing_if = "Option::is_none")]
    pub locality: Option<Vec<String>>,
    /// If set, O (Organization) will be set to this value.
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Vec<String>>,
    /// Requested other SANs, in an array with the format <oid>;UTF8:<utf8 string value> for each entry.
    #[serde(rename = "other_sans", skip_serializing_if = "Option::is_none")]
    pub other_sans: Option<Vec<String>>,
    /// If set, OU (OrganizationalUnit) will be set to this value.
    #[serde(rename = "ou", skip_serializing_if = "Option::is_none")]
    pub ou: Option<Vec<String>>,
    /// If set, Postal Code will be set to this value.
    #[serde(rename = "postal_code", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Vec<String>>,
    /// Format for the returned private key. Generally the default will be controlled by the \"format\" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to \"pkcs8\" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to \"der\".
    #[serde(rename = "private_key_format", skip_serializing_if = "Option::is_none")]
    pub private_key_format: Option<PrivateKeyFormat>,
    /// If set, Province will be set to this value.
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<Vec<String>>,
    /// The requested serial number, if any. If you want more than one, specify alternative names in the alt_names map using OID 2.5.4.5.
    #[serde(rename = "serial_number", skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    /// If set, Street Address will be set to this value.
    #[serde(rename = "street_address", skip_serializing_if = "Option::is_none")]
    pub street_address: Option<Vec<String>>,
    /// The requested Time To Live for the certificate; sets the expiration date. If not specified the role default, backend default, or system default TTL is used, in that order. Cannot be larger than the mount max TTL. Note: this only has an effect when generating a CA cert or signing a CA cert, not when generating a CSR for an intermediate CA.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// The requested URI SANs, if any, in a comma-delimited list.
    #[serde(rename = "uri_sans", skip_serializing_if = "Option::is_none")]
    pub uri_sans: Option<Vec<String>>,
}

impl InlineObject164 {
    pub fn new() -> InlineObject164 {
        InlineObject164 {
            add_basic_constraints: None,
            alt_names: None,
            common_name: None,
            country: None,
            exclude_cn_from_sans: None,
            format: None,
            ip_sans: None,
            key_bits: None,
            key_type: None,
            locality: None,
            organization: None,
            other_sans: None,
            ou: None,
            postal_code: None,
            private_key_format: None,
            province: None,
            serial_number: None,
            street_address: None,
            ttl: None,
            uri_sans: None,
        }
    }
}

/// Format for returned data. Can be \"pem\", \"der\", or \"pem_bundle\". If \"pem_bundle\" any private key and issuing cert will be appended to the certificate pem. Defaults to \"pem\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "pem")]
    Pem,
    #[serde(rename = "der")]
    Der,
    #[serde(rename = "pem_bundle")]
    PemBundle,
}
/// The type of key to use; defaults to RSA. \"rsa\" and \"ec\" are the only valid values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "rsa")]
    Rsa,
    #[serde(rename = "ec")]
    Ec,
}
/// Format for the returned private key. Generally the default will be controlled by the \"format\" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to \"pkcs8\" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to \"der\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrivateKeyFormat {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "der")]
    Der,
    #[serde(rename = "pem")]
    Pem,
    #[serde(rename = "pkcs8")]
    Pkcs8,
}

