/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject23 {
    /// Duration in seconds after which the issued SecretID should expire. Defaults to 0, meaning no expiration.
    #[serde(rename = "secret_id_ttl", skip_serializing_if = "Option::is_none")]
    pub secret_id_ttl: Option<i32>,
}

impl InlineObject23 {
    pub fn new() -> InlineObject23 {
        InlineObject23 {
            secret_id_ttl: None,
        }
    }
}


