/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject44 {
    /// A comma-separated list of names. At least one must exist in the Common Name. Supports globbing.
    #[serde(rename = "allowed_common_names", skip_serializing_if = "Option::is_none")]
    pub allowed_common_names: Option<Vec<String>>,
    /// A comma-separated list of DNS names. At least one must exist in the SANs. Supports globbing.
    #[serde(rename = "allowed_dns_sans", skip_serializing_if = "Option::is_none")]
    pub allowed_dns_sans: Option<Vec<String>>,
    /// A comma-separated list of Email Addresses. At least one must exist in the SANs. Supports globbing.
    #[serde(rename = "allowed_email_sans", skip_serializing_if = "Option::is_none")]
    pub allowed_email_sans: Option<Vec<String>>,
    /// A comma-separated list of names. At least one must exist in either the Common Name or SANs. Supports globbing. This parameter is deprecated, please use allowed_common_names, allowed_dns_sans, allowed_email_sans, allowed_uri_sans.
    #[serde(rename = "allowed_names", skip_serializing_if = "Option::is_none")]
    pub allowed_names: Option<Vec<String>>,
    /// A comma-separated list of Organizational Units names. At least one must exist in the OU field.
    #[serde(rename = "allowed_organizational_units", skip_serializing_if = "Option::is_none")]
    pub allowed_organizational_units: Option<Vec<String>>,
    /// A comma-separated list of URIs. At least one must exist in the SANs. Supports globbing.
    #[serde(rename = "allowed_uri_sans", skip_serializing_if = "Option::is_none")]
    pub allowed_uri_sans: Option<Vec<String>>,
    /// Use \"token_bound_cidrs\" instead. If this and \"token_bound_cidrs\" are both specified, only \"token_bound_cidrs\" will be used.
    #[serde(rename = "bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub bound_cidrs: Option<Vec<String>>,
    /// The public certificate that should be trusted. Must be x509 PEM encoded.
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    /// The display name to use for clients using this certificate.
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Use \"token_ttl\" instead. If this and \"token_ttl\" are both specified, only \"token_ttl\" will be used.
    #[serde(rename = "lease", skip_serializing_if = "Option::is_none")]
    pub lease: Option<i32>,
    /// Use \"token_max_ttl\" instead. If this and \"token_max_ttl\" are both specified, only \"token_max_ttl\" will be used.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Use \"token_period\" instead. If this and \"token_period\" are both specified, only \"token_period\" will be used.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// Use \"token_policies\" instead. If this and \"token_policies\" are both specified, only \"token_policies\" will be used.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// A comma-separated string or array of extensions formatted as \"oid:value\". Expects the extension value to be some type of ASN1 encoded string. All values much match. Supports globbing on \"value\".
    #[serde(rename = "required_extensions", skip_serializing_if = "Option::is_none")]
    pub required_extensions: Option<Vec<String>>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// The maximum lifetime of the generated token
    #[serde(rename = "token_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// Comma-separated list of policies
    #[serde(rename = "token_policies", skip_serializing_if = "Option::is_none")]
    pub token_policies: Option<Vec<String>>,
    /// The initial ttl of the token to generate
    #[serde(rename = "token_ttl", skip_serializing_if = "Option::is_none")]
    pub token_ttl: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    /// Use \"token_ttl\" instead. If this and \"token_ttl\" are both specified, only \"token_ttl\" will be used.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl InlineObject44 {
    pub fn new() -> InlineObject44 {
        InlineObject44 {
            allowed_common_names: None,
            allowed_dns_sans: None,
            allowed_email_sans: None,
            allowed_names: None,
            allowed_organizational_units: None,
            allowed_uri_sans: None,
            bound_cidrs: None,
            certificate: None,
            display_name: None,
            lease: None,
            max_ttl: None,
            period: None,
            policies: None,
            required_extensions: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_policies: None,
            token_ttl: None,
            token_type: None,
            ttl: None,
        }
    }
}


