/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject233 {
    /// Whether or not to perform the revocation synchronously
    #[serde(rename = "sync", skip_serializing_if = "Option::is_none")]
    pub sync: Option<bool>,
}

impl InlineObject233 {
    pub fn new() -> InlineObject233 {
        InlineObject233 {
            sync: None,
        }
    }
}


