/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject148 {
    /// ID of the group. If set, updates the corresponding existing group.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Entity IDs to be assigned as group members.
    #[serde(rename = "member_entity_ids", skip_serializing_if = "Option::is_none")]
    pub member_entity_ids: Option<Vec<String>>,
    /// Group IDs to be assigned as group members.
    #[serde(rename = "member_group_ids", skip_serializing_if = "Option::is_none")]
    pub member_group_ids: Option<Vec<String>>,
    /// Metadata to be associated with the group. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: vault <command> <path> metadata=key1=value1 metadata=key2=value2
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// Policies to be tied to the group.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// Type of the group, 'internal' or 'external'. Defaults to 'internal'
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl InlineObject148 {
    pub fn new() -> InlineObject148 {
        InlineObject148 {
            id: None,
            member_entity_ids: None,
            member_group_ids: None,
            metadata: None,
            policies: None,
            _type: None,
        }
    }
}


