/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject81 {
    /// Duo api host
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Duo integration key
    #[serde(rename = "ikey", skip_serializing_if = "Option::is_none")]
    pub ikey: Option<String>,
    /// Duo secret key
    #[serde(rename = "skey", skip_serializing_if = "Option::is_none")]
    pub skey: Option<String>,
}

impl InlineObject81 {
    pub fn new() -> InlineObject81 {
        InlineObject81 {
            host: None,
            ikey: None,
            skey: None,
        }
    }
}


