/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject35 {
    /// If set to 'true', disables the periodic tidying of blacklisted entries.
    #[serde(rename = "disable_periodic_tidy", skip_serializing_if = "Option::is_none")]
    pub disable_periodic_tidy: Option<bool>,
    /// The amount of extra time that must have passed beyond the roletag expiration, before it is removed from the backend storage. Defaults to 4320h (180 days).
    #[serde(rename = "safety_buffer", skip_serializing_if = "Option::is_none")]
    pub safety_buffer: Option<i32>,
}

impl InlineObject35 {
    pub fn new() -> InlineObject35 {
        InlineObject35 {
            disable_periodic_tidy: None,
            safety_buffer: None,
        }
    }
}


