/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject170 {
    /// The requested Subject Alternative Names, if any, in a comma-delimited list. May contain both DNS names and email addresses.
    #[serde(rename = "alt_names", skip_serializing_if = "Option::is_none")]
    pub alt_names: Option<String>,
    /// The requested common name; if you want more than one, specify the alternative names in the alt_names map. If not specified when signing, the common name will be taken from the CSR; other names must still be specified in alt_names or ip_sans.
    #[serde(rename = "common_name", skip_serializing_if = "Option::is_none")]
    pub common_name: Option<String>,
    /// If set, Country will be set to this value.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<Vec<String>>,
    /// PEM-format CSR to be signed.
    #[serde(rename = "csr", skip_serializing_if = "Option::is_none")]
    pub csr: Option<String>,
    /// If true, the Common Name will not be included in DNS or Email Subject Alternate Names. Defaults to false (CN is included).
    #[serde(rename = "exclude_cn_from_sans", skip_serializing_if = "Option::is_none")]
    pub exclude_cn_from_sans: Option<bool>,
    /// Format for returned data. Can be \"pem\", \"der\", or \"pem_bundle\". If \"pem_bundle\" any private key and issuing cert will be appended to the certificate pem. Defaults to \"pem\".
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// The requested IP SANs, if any, in a comma-delimited list
    #[serde(rename = "ip_sans", skip_serializing_if = "Option::is_none")]
    pub ip_sans: Option<Vec<String>>,
    /// If set, Locality will be set to this value.
    #[serde(rename = "locality", skip_serializing_if = "Option::is_none")]
    pub locality: Option<Vec<String>>,
    /// The maximum allowable path length
    #[serde(rename = "max_path_length", skip_serializing_if = "Option::is_none")]
    pub max_path_length: Option<i32>,
    /// If set, O (Organization) will be set to this value.
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Vec<String>>,
    /// Requested other SANs, in an array with the format <oid>;UTF8:<utf8 string value> for each entry.
    #[serde(rename = "other_sans", skip_serializing_if = "Option::is_none")]
    pub other_sans: Option<Vec<String>>,
    /// If set, OU (OrganizationalUnit) will be set to this value.
    #[serde(rename = "ou", skip_serializing_if = "Option::is_none")]
    pub ou: Option<Vec<String>>,
    /// Domains for which this certificate is allowed to sign or issue child certificates. If set, all DNS names (subject and alt) on child certs must be exact matches or subsets of the given domains (see https://tools.ietf.org/html/rfc5280#section-4.2.1.10).
    #[serde(rename = "permitted_dns_domains", skip_serializing_if = "Option::is_none")]
    pub permitted_dns_domains: Option<Vec<String>>,
    /// If set, Postal Code will be set to this value.
    #[serde(rename = "postal_code", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Vec<String>>,
    /// Format for the returned private key. Generally the default will be controlled by the \"format\" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to \"pkcs8\" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to \"der\".
    #[serde(rename = "private_key_format", skip_serializing_if = "Option::is_none")]
    pub private_key_format: Option<PrivateKeyFormat>,
    /// If set, Province will be set to this value.
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<Vec<String>>,
    /// The requested serial number, if any. If you want more than one, specify alternative names in the alt_names map using OID 2.5.4.5.
    #[serde(rename = "serial_number", skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    /// If set, Street Address will be set to this value.
    #[serde(rename = "street_address", skip_serializing_if = "Option::is_none")]
    pub street_address: Option<Vec<String>>,
    /// The requested Time To Live for the certificate; sets the expiration date. If not specified the role default, backend default, or system default TTL is used, in that order. Cannot be larger than the mount max TTL. Note: this only has an effect when generating a CA cert or signing a CA cert, not when generating a CSR for an intermediate CA.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// The requested URI SANs, if any, in a comma-delimited list.
    #[serde(rename = "uri_sans", skip_serializing_if = "Option::is_none")]
    pub uri_sans: Option<Vec<String>>,
    /// If true, then: 1) Subject information, including names and alternate names, will be preserved from the CSR rather than using values provided in the other parameters to this path; 2) Any key usages requested in the CSR will be added to the basic set of key usages used for CA certs signed by this path; for instance, the non-repudiation flag.
    #[serde(rename = "use_csr_values", skip_serializing_if = "Option::is_none")]
    pub use_csr_values: Option<bool>,
}

impl InlineObject170 {
    pub fn new() -> InlineObject170 {
        InlineObject170 {
            alt_names: None,
            common_name: None,
            country: None,
            csr: None,
            exclude_cn_from_sans: None,
            format: None,
            ip_sans: None,
            locality: None,
            max_path_length: None,
            organization: None,
            other_sans: None,
            ou: None,
            permitted_dns_domains: None,
            postal_code: None,
            private_key_format: None,
            province: None,
            serial_number: None,
            street_address: None,
            ttl: None,
            uri_sans: None,
            use_csr_values: None,
        }
    }
}

/// Format for returned data. Can be \"pem\", \"der\", or \"pem_bundle\". If \"pem_bundle\" any private key and issuing cert will be appended to the certificate pem. Defaults to \"pem\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "pem")]
    Pem,
    #[serde(rename = "der")]
    Der,
    #[serde(rename = "pem_bundle")]
    PemBundle,
}
/// Format for the returned private key. Generally the default will be controlled by the \"format\" parameter as either base64-encoded DER or PEM-encoded DER. However, this can be set to \"pkcs8\" to have the returned private key contain base64-encoded pkcs8 or PEM-encoded pkcs8 instead. Defaults to \"der\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrivateKeyFormat {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "der")]
    Der,
    #[serde(rename = "pem")]
    Pem,
    #[serde(rename = "pkcs8")]
    Pkcs8,
}

