/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject114 {
    /// Use role_arns or policy_arns instead.
    #[serde(rename = "arn", skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
    /// Type of credential to retrieve. Must be one of assumed_role, iam_user, or federation_token
    #[serde(rename = "credential_type", skip_serializing_if = "Option::is_none")]
    pub credential_type: Option<String>,
    /// Default TTL for assumed_role and federation_token credential types when no TTL is explicitly requested with the credentials
    #[serde(rename = "default_sts_ttl", skip_serializing_if = "Option::is_none")]
    pub default_sts_ttl: Option<i32>,
    /// Names of IAM groups that generated IAM users will be added to. For a credential type of assumed_role or federation_token, the policies sent to the corresponding AWS call (sts:AssumeRole or sts:GetFederation) will be the policies from each group in iam_groups combined with the policy_document and policy_arns parameters.
    #[serde(rename = "iam_groups", skip_serializing_if = "Option::is_none")]
    pub iam_groups: Option<Vec<String>>,
    /// Max allowed TTL for assumed_role and federation_token credential types
    #[serde(rename = "max_sts_ttl", skip_serializing_if = "Option::is_none")]
    pub max_sts_ttl: Option<i32>,
    /// ARN of an IAM policy to attach as a permissions boundary on IAM user credentials; only valid when credential_type isiam_user
    #[serde(rename = "permissions_boundary_arn", skip_serializing_if = "Option::is_none")]
    pub permissions_boundary_arn: Option<String>,
    /// Use policy_document instead.
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    /// ARNs of AWS policies. Behavior varies by credential_type. When credential_type is iam_user, then it will attach the specified policies to the generated IAM user. When credential_type is assumed_role or federation_token, the policies will be passed as the PolicyArns parameter, acting as a filter on permissions available.
    #[serde(rename = "policy_arns", skip_serializing_if = "Option::is_none")]
    pub policy_arns: Option<Vec<String>>,
    /// JSON-encoded IAM policy document. Behavior varies by credential_type. When credential_type is iam_user, then it will attach the contents of the policy_document to the IAM user generated. When credential_type is assumed_role or federation_token, this will be passed in as the Policy parameter to the AssumeRole or GetFederationToken API call, acting as a filter on permissions available.
    #[serde(rename = "policy_document", skip_serializing_if = "Option::is_none")]
    pub policy_document: Option<String>,
    /// ARNs of AWS roles allowed to be assumed. Only valid when credential_type is assumed_role
    #[serde(rename = "role_arns", skip_serializing_if = "Option::is_none")]
    pub role_arns: Option<Vec<String>>,
    /// Path for IAM User. Only valid when credential_type is iam_user
    #[serde(rename = "user_path", skip_serializing_if = "Option::is_none")]
    pub user_path: Option<String>,
}

impl InlineObject114 {
    pub fn new() -> InlineObject114 {
        InlineObject114 {
            arn: None,
            credential_type: None,
            default_sts_ttl: None,
            iam_groups: None,
            max_sts_ttl: None,
            permissions_boundary_arn: None,
            policy: None,
            policy_arns: None,
            policy_document: None,
            role_arns: None,
            user_path: None,
        }
    }
}


