/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject209 {
    /// The desired increment in seconds to the lease
    #[serde(rename = "increment", skip_serializing_if = "Option::is_none")]
    pub increment: Option<i32>,
    /// The lease identifier to renew. This is included with a lease.
    #[serde(rename = "lease_id", skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<String>,
    /// The lease identifier to renew. This is included with a lease.
    #[serde(rename = "url_lease_id", skip_serializing_if = "Option::is_none")]
    pub url_lease_id: Option<String>,
}

impl InlineObject209 {
    pub fn new() -> InlineObject209 {
        InlineObject209 {
            increment: None,
            lease_id: None,
            url_lease_id: None,
        }
    }
}


