/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject42 {
    /// A signed JWT
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// The resource group from the instance.
    #[serde(rename = "resource_group_name", skip_serializing_if = "Option::is_none")]
    pub resource_group_name: Option<String>,
    /// The token role.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// The subscription id for the instance.
    #[serde(rename = "subscription_id", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
    /// The name of the virtual machine. This value is ignored if vmss_name is specified.
    #[serde(rename = "vm_name", skip_serializing_if = "Option::is_none")]
    pub vm_name: Option<String>,
    /// The name of the virtual machine scale set the instance is in.
    #[serde(rename = "vmss_name", skip_serializing_if = "Option::is_none")]
    pub vmss_name: Option<String>,
}

impl InlineObject42 {
    pub fn new() -> InlineObject42 {
        InlineObject42 {
            jwt: None,
            resource_group_name: None,
            role: None,
            subscription_id: None,
            vm_name: None,
            vmss_name: None,
        }
    }
}


