/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject204 {
    /// Specifies a base64-encoded PGP public key.
    #[serde(rename = "pgp_key", skip_serializing_if = "Option::is_none")]
    pub pgp_key: Option<String>,
}

impl InlineObject204 {
    pub fn new() -> InlineObject204 {
        InlineObject204 {
            pgp_key: None,
        }
    }
}


