/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject87 {
    /// Number of seconds before connect times out (default: 10)
    #[serde(rename = "dial_timeout", skip_serializing_if = "Option::is_none")]
    pub dial_timeout: Option<i32>,
    /// RADIUS server host
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// RADIUS NAS Identifier field (optional)
    #[serde(rename = "nas_identifier", skip_serializing_if = "Option::is_none")]
    pub nas_identifier: Option<String>,
    /// RADIUS NAS port field (default: 10)
    #[serde(rename = "nas_port", skip_serializing_if = "Option::is_none")]
    pub nas_port: Option<i32>,
    /// RADIUS server port (default: 1812)
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// Number of seconds before response times out (default: 10)
    #[serde(rename = "read_timeout", skip_serializing_if = "Option::is_none")]
    pub read_timeout: Option<i32>,
    /// Secret shared with the RADIUS server
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// The maximum lifetime of the generated token
    #[serde(rename = "token_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// Comma-separated list of policies. This will apply to all tokens generated by this auth method, in addition to any configured for specific users.
    #[serde(rename = "token_policies", skip_serializing_if = "Option::is_none")]
    pub token_policies: Option<Vec<String>>,
    /// The initial ttl of the token to generate
    #[serde(rename = "token_ttl", skip_serializing_if = "Option::is_none")]
    pub token_ttl: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    /// Comma-separated list of policies to grant upon successful RADIUS authentication of an unregisted user (default: empty)
    #[serde(rename = "unregistered_user_policies", skip_serializing_if = "Option::is_none")]
    pub unregistered_user_policies: Option<String>,
}

impl InlineObject87 {
    pub fn new() -> InlineObject87 {
        InlineObject87 {
            dial_timeout: None,
            host: None,
            nas_identifier: None,
            nas_port: None,
            port: None,
            read_timeout: None,
            secret: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_policies: None,
            token_ttl: None,
            token_type: None,
            unregistered_user_policies: None,
        }
    }
}


