/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject32 {
    /// Configure how the AWS auth method generates entity alias when using EC2 auth. Valid values are \"role_id\", \"instance_id\", and \"image_id\". Defaults to \"role_id\".
    #[serde(rename = "ec2_alias", skip_serializing_if = "Option::is_none")]
    pub ec2_alias: Option<String>,
    /// The metadata to include on the aliases and audit logs generated by this plugin. When set to 'default', includes: account_id, auth_type. These fields are available to add: ami_id, instance_id, region. Not editing this field means the 'default' fields are included. Explicitly setting this field to empty overrides the 'default' and means no metadata will be included. If not using 'default', explicit fields must be sent like: 'field1,field2'.
    #[serde(rename = "ec2_metadata", skip_serializing_if = "Option::is_none")]
    pub ec2_metadata: Option<Vec<String>>,
    /// Configure how the AWS auth method generates entity aliases when using IAM auth. Valid values are \"role_id\", \"unique_id\", and \"full_arn\". Defaults to \"role_id\".
    #[serde(rename = "iam_alias", skip_serializing_if = "Option::is_none")]
    pub iam_alias: Option<String>,
    /// The metadata to include on the aliases and audit logs generated by this plugin. When set to 'default', includes: account_id, auth_type. These fields are available to add: canonical_arn, client_arn, client_user_id, inferred_aws_region, inferred_entity_id, inferred_entity_type. Not editing this field means the 'default' fields are included. Explicitly setting this field to empty overrides the 'default' and means no metadata will be included. If not using 'default', explicit fields must be sent like: 'field1,field2'.
    #[serde(rename = "iam_metadata", skip_serializing_if = "Option::is_none")]
    pub iam_metadata: Option<Vec<String>>,
}

impl InlineObject32 {
    pub fn new() -> InlineObject32 {
        InlineObject32 {
            ec2_alias: None,
            ec2_metadata: None,
            iam_alias: None,
            iam_metadata: None,
        }
    }
}


