/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject167 {
    /// Certificate serial number, in colon- or hyphen-separated octal
    #[serde(rename = "serial_number", skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
}

impl InlineObject167 {
    pub fn new() -> InlineObject167 {
        InlineObject167 {
            serial_number: None,
        }
    }
}


