/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject206 {
    /// Specifies an array of PGP public keys used to encrypt the output unseal keys. Ordering is preserved. The keys must be base64-encoded from their original binary representation. The size of this array must be the same as `secret_shares`.
    #[serde(rename = "pgp_keys", skip_serializing_if = "Option::is_none")]
    pub pgp_keys: Option<Vec<String>>,
    /// Specifies an array of PGP public keys used to encrypt the output recovery keys. Ordering is preserved. The keys must be base64-encoded from their original binary representation. The size of this array must be the same as `recovery_shares`.
    #[serde(rename = "recovery_pgp_keys", skip_serializing_if = "Option::is_none")]
    pub recovery_pgp_keys: Option<Vec<String>>,
    /// Specifies the number of shares to split the recovery key into.
    #[serde(rename = "recovery_shares", skip_serializing_if = "Option::is_none")]
    pub recovery_shares: Option<i32>,
    /// Specifies the number of shares required to reconstruct the recovery key. This must be less than or equal to `recovery_shares`.
    #[serde(rename = "recovery_threshold", skip_serializing_if = "Option::is_none")]
    pub recovery_threshold: Option<i32>,
    /// Specifies a PGP public key used to encrypt the initial root token. The key must be base64-encoded from its original binary representation.
    #[serde(rename = "root_token_pgp_key", skip_serializing_if = "Option::is_none")]
    pub root_token_pgp_key: Option<String>,
    /// Specifies the number of shares to split the master key into.
    #[serde(rename = "secret_shares", skip_serializing_if = "Option::is_none")]
    pub secret_shares: Option<i32>,
    /// Specifies the number of shares required to reconstruct the master key. This must be less than or equal secret_shares. If using Vault HSM with auto-unsealing, this value must be the same as `secret_shares`.
    #[serde(rename = "secret_threshold", skip_serializing_if = "Option::is_none")]
    pub secret_threshold: Option<i32>,
    /// Specifies the number of shares that should be encrypted by the HSM and stored for auto-unsealing. Currently must be the same as `secret_shares`.
    #[serde(rename = "stored_shares", skip_serializing_if = "Option::is_none")]
    pub stored_shares: Option<i32>,
}

impl InlineObject206 {
    pub fn new() -> InlineObject206 {
        InlineObject206 {
            pgp_keys: None,
            recovery_pgp_keys: None,
            recovery_shares: None,
            recovery_threshold: None,
            root_token_pgp_key: None,
            secret_shares: None,
            secret_threshold: None,
            stored_shares: None,
        }
    }
}


