/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject31 {
    /// AWS Access Key ID for the account used to make AWS API requests.
    #[serde(rename = "access_key", skip_serializing_if = "Option::is_none")]
    pub access_key: Option<String>,
    /// List of additional headers that are allowed to be in AWS STS request headers
    #[serde(rename = "allowed_sts_header_values", skip_serializing_if = "Option::is_none")]
    pub allowed_sts_header_values: Option<Vec<String>>,
    /// URL to override the default generated endpoint for making AWS EC2 API calls.
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    /// URL to override the default generated endpoint for making AWS IAM API calls.
    #[serde(rename = "iam_endpoint", skip_serializing_if = "Option::is_none")]
    pub iam_endpoint: Option<String>,
    /// Value to require in the X-Vault-AWS-IAM-Server-ID request header
    #[serde(rename = "iam_server_id_header_value", skip_serializing_if = "Option::is_none")]
    pub iam_server_id_header_value: Option<String>,
    /// Maximum number of retries for recoverable exceptions of AWS APIs
    #[serde(rename = "max_retries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
    /// AWS Secret Access Key for the account used to make AWS API requests.
    #[serde(rename = "secret_key", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    /// URL to override the default generated endpoint for making AWS STS API calls.
    #[serde(rename = "sts_endpoint", skip_serializing_if = "Option::is_none")]
    pub sts_endpoint: Option<String>,
    /// The region ID for the sts_endpoint, if set.
    #[serde(rename = "sts_region", skip_serializing_if = "Option::is_none")]
    pub sts_region: Option<String>,
}

impl InlineObject31 {
    pub fn new() -> InlineObject31 {
        InlineObject31 {
            access_key: None,
            allowed_sts_header_values: None,
            endpoint: None,
            iam_endpoint: None,
            iam_server_id_header_value: None,
            max_retries: None,
            secret_key: None,
            sts_endpoint: None,
            sts_region: None,
        }
    }
}


