/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject179 {
    /// If true, the backend will require the cas parameter to be set for each write
    #[serde(rename = "cas_required", skip_serializing_if = "Option::is_none")]
    pub cas_required: Option<bool>,
    /// If set, the length of time before a version is deleted. A negative duration disables the use of delete_version_after on all keys. A zero duration clears the current setting. Accepts a Go duration format string.
    #[serde(rename = "delete_version_after", skip_serializing_if = "Option::is_none")]
    pub delete_version_after: Option<i32>,
    /// The number of versions to keep for each key. Defaults to 10
    #[serde(rename = "max_versions", skip_serializing_if = "Option::is_none")]
    pub max_versions: Option<i32>,
}

impl InlineObject179 {
    pub fn new() -> InlineObject179 {
        InlineObject179 {
            cas_required: None,
            delete_version_after: None,
            max_versions: None,
        }
    }
}


