/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject161 {
    /// PEM-format, concatenated unencrypted secret key and certificate.
    #[serde(rename = "pem_bundle", skip_serializing_if = "Option::is_none")]
    pub pem_bundle: Option<String>,
}

impl InlineObject161 {
    pub fn new() -> InlineObject161 {
        InlineObject161 {
            pem_bundle: None,
        }
    }
}


