/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject13 {
    /// Deprecated: Please use \"secret_id_bound_cidrs\" instead. Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can perform the login operation.
    #[serde(rename = "bound_cidr_list", skip_serializing_if = "Option::is_none")]
    pub bound_cidr_list: Option<Vec<String>>,
}

impl InlineObject13 {
    pub fn new() -> InlineObject13 {
        InlineObject13 {
            bound_cidr_list: None,
        }
    }
}


