/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject103 {
    /// String or JSON list of allowed entity aliases. If set, specifies the entity aliases which are allowed to be used during token generation. This field supports globbing.
    #[serde(rename = "allowed_entity_aliases", skip_serializing_if = "Option::is_none")]
    pub allowed_entity_aliases: Option<Vec<String>>,
    /// If set, tokens can be created with any subset of the policies in this list, rather than the normal semantics of tokens being a subset of the calling token's policies. The parameter is a comma-delimited string of policy names.
    #[serde(rename = "allowed_policies", skip_serializing_if = "Option::is_none")]
    pub allowed_policies: Option<Vec<String>>,
    /// Use 'token_bound_cidrs' instead.
    #[serde(rename = "bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub bound_cidrs: Option<Vec<String>>,
    /// If set, successful token creation via this role will require that no policies in the given list are requested. The parameter is a comma-delimited string of policy names.
    #[serde(rename = "disallowed_policies", skip_serializing_if = "Option::is_none")]
    pub disallowed_policies: Option<Vec<String>>,
    /// Use 'token_explicit_max_ttl' instead.
    #[serde(rename = "explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub explicit_max_ttl: Option<i32>,
    /// If true, tokens created via this role will be orphan tokens (have no parent)
    #[serde(rename = "orphan", skip_serializing_if = "Option::is_none")]
    pub orphan: Option<bool>,
    /// If set, tokens created via this role will contain the given suffix as a part of their path. This can be used to assist use of the 'revoke-prefix' endpoint later on. The given suffix must match the regular expression.\\w[\\w-.]+\\w
    #[serde(rename = "path_suffix", skip_serializing_if = "Option::is_none")]
    pub path_suffix: Option<String>,
    /// Use 'token_period' instead.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// Tokens created via this role will be renewable or not according to this value. Defaults to \"true\".
    #[serde(rename = "renewable", skip_serializing_if = "Option::is_none")]
    pub renewable: Option<bool>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
}

impl InlineObject103 {
    pub fn new() -> InlineObject103 {
        InlineObject103 {
            allowed_entity_aliases: None,
            allowed_policies: None,
            bound_cidrs: None,
            disallowed_policies: None,
            explicit_max_ttl: None,
            orphan: None,
            path_suffix: None,
            period: None,
            renewable: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_type: None,
        }
    }
}


