/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject142 {
    /// Setting this will follow the 'mine' strategy for merging MFA secrets. If there are secrets of the same type both in entities that are merged from and in entity into which all others are getting merged, secrets in the destination will be unaltered. If not set, this API will throw an error containing all the conflicts.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    /// Entity IDs which needs to get merged
    #[serde(rename = "from_entity_ids", skip_serializing_if = "Option::is_none")]
    pub from_entity_ids: Option<Vec<String>>,
    /// Entity ID into which all the other entities need to get merged
    #[serde(rename = "to_entity_id", skip_serializing_if = "Option::is_none")]
    pub to_entity_id: Option<String>,
}

impl InlineObject142 {
    pub fn new() -> InlineObject142 {
        InlineObject142 {
            force: None,
            from_entity_ids: None,
            to_entity_id: None,
        }
    }
}


