/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject33 {
    /// AWS ARN for STS role to be assumed when interacting with the account specified. The Vault server must have permissions to assume this role.
    #[serde(rename = "sts_role", skip_serializing_if = "Option::is_none")]
    pub sts_role: Option<String>,
}

impl InlineObject33 {
    pub fn new() -> InlineObject33 {
        InlineObject33 {
            sts_role: None,
        }
    }
}


