/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject50 {
    /// If true, will add group aliases to auth tokens generated under this role. This will add the full list of ancestors (projects, folders, organizations) for the given entity's project. Requires IAM permission `resourcemanager.projects.get` on this project.
    #[serde(rename = "add_group_aliases", skip_serializing_if = "Option::is_none")]
    pub add_group_aliases: Option<bool>,
    /// 'iam' roles only. If false, Vault will not not allow GCE instances to login in against this role
    #[serde(rename = "allow_gce_inference", skip_serializing_if = "Option::is_none")]
    pub allow_gce_inference: Option<bool>,
    /// Deprecated: use \"bound_instance_groups\" instead.
    #[serde(rename = "bound_instance_group", skip_serializing_if = "Option::is_none")]
    pub bound_instance_group: Option<String>,
    /// Comma-separated list of permitted instance groups to which the GCE instance must belong. This option only applies to \"gce\" roles.
    #[serde(rename = "bound_instance_groups", skip_serializing_if = "Option::is_none")]
    pub bound_instance_groups: Option<Vec<String>>,
    /// Comma-separated list of GCP labels formatted as\"key:value\" strings that must be present on the GCE instance in order to authenticate. This option only applies to \"gce\" roles.
    #[serde(rename = "bound_labels", skip_serializing_if = "Option::is_none")]
    pub bound_labels: Option<Vec<String>>,
    /// GCP Projects that authenticating entities must belong to.
    #[serde(rename = "bound_projects", skip_serializing_if = "Option::is_none")]
    pub bound_projects: Option<Vec<String>>,
    /// Deprecated: use \"bound_regions\" instead.
    #[serde(rename = "bound_region", skip_serializing_if = "Option::is_none")]
    pub bound_region: Option<String>,
    /// Comma-separated list of permitted regions to which the GCE instance must belong. If a group is provided, it is assumed to be a regional group. If \"zone\" is provided, this option is ignored. This can be a self-link or region name. This option only applies to \"gce\" roles.
    #[serde(rename = "bound_regions", skip_serializing_if = "Option::is_none")]
    pub bound_regions: Option<Vec<String>>,
    /// Can be set for both 'iam' and 'gce' roles (required for 'iam'). A comma-seperated list of authorized service accounts. If the single value \"*\" is given, this is assumed to be all service accounts under the role's project. If this is set on a GCE role, the inferred service account from the instance metadata token will be used.
    #[serde(rename = "bound_service_accounts", skip_serializing_if = "Option::is_none")]
    pub bound_service_accounts: Option<Vec<String>>,
    /// Deprecated: use \"bound_zones\" instead.
    #[serde(rename = "bound_zone", skip_serializing_if = "Option::is_none")]
    pub bound_zone: Option<String>,
    /// Comma-separated list of permitted zones to which the GCE instance must belong. If a group is provided, it is assumed to be a zonal group. This can be a self-link or zone name. This option only applies to \"gce\" roles.
    #[serde(rename = "bound_zones", skip_serializing_if = "Option::is_none")]
    pub bound_zones: Option<Vec<String>>,
    /// Currently enabled for 'iam' only. Duration in seconds from time of validation that a JWT must expire within.
    #[serde(rename = "max_jwt_exp", skip_serializing_if = "Option::is_none")]
    pub max_jwt_exp: Option<i32>,
    /// Use \"token_max_ttl\" instead. If this and \"token_max_ttl\" are both specified, only \"token_max_ttl\" will be used.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Use \"token_period\" instead. If this and \"token_period\" are both specified, only \"token_period\" will be used.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// Use \"token_policies\" instead. If this and \"token_policies\" are both specified, only \"token_policies\" will be used.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// Deprecated: use \"bound_projects\" instead
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// Deprecated: use \"bound_service_accounts\" instead.
    #[serde(rename = "service_accounts", skip_serializing_if = "Option::is_none")]
    pub service_accounts: Option<Vec<String>>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// The maximum lifetime of the generated token
    #[serde(rename = "token_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// Comma-separated list of policies
    #[serde(rename = "token_policies", skip_serializing_if = "Option::is_none")]
    pub token_policies: Option<Vec<String>>,
    /// The initial ttl of the token to generate
    #[serde(rename = "token_ttl", skip_serializing_if = "Option::is_none")]
    pub token_ttl: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    /// Use \"token_ttl\" instead. If this and \"token_ttl\" are both specified, only \"token_ttl\" will be used.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// Type of the role. Currently supported: iam, gce
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl InlineObject50 {
    pub fn new() -> InlineObject50 {
        InlineObject50 {
            add_group_aliases: None,
            allow_gce_inference: None,
            bound_instance_group: None,
            bound_instance_groups: None,
            bound_labels: None,
            bound_projects: None,
            bound_region: None,
            bound_regions: None,
            bound_service_accounts: None,
            bound_zone: None,
            bound_zones: None,
            max_jwt_exp: None,
            max_ttl: None,
            period: None,
            policies: None,
            project_id: None,
            service_accounts: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_policies: None,
            token_ttl: None,
            token_type: None,
            ttl: None,
            _type: None,
        }
    }
}


