/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject22 {
    /// Number of times a SecretID can access the role, after which the SecretID will expire.
    #[serde(rename = "secret_id_num_uses", skip_serializing_if = "Option::is_none")]
    pub secret_id_num_uses: Option<i32>,
}

impl InlineObject22 {
    pub fn new() -> InlineObject22 {
        InlineObject22 {
            secret_id_num_uses: None,
        }
    }
}


