/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject5 {
    /// The username/logon name for the service account with which this role will be associated.
    #[serde(rename = "service_account_name", skip_serializing_if = "Option::is_none")]
    pub service_account_name: Option<String>,
    /// In seconds, the default password time-to-live.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl InlineObject5 {
    pub fn new() -> InlineObject5 {
        InlineObject5 {
            service_account_name: None,
            ttl: None,
        }
    }
}


