/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject62 {
    /// Optional client-provided nonce that must match during callback, if present.
    #[serde(rename = "client_nonce", skip_serializing_if = "Option::is_none")]
    pub client_nonce: Option<String>,
    /// The OAuth redirect_uri to use in the authorization URL.
    #[serde(rename = "redirect_uri", skip_serializing_if = "Option::is_none")]
    pub redirect_uri: Option<String>,
    /// The role to issue an OIDC authorization URL against.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
}

impl InlineObject62 {
    pub fn new() -> InlineObject62 {
        InlineObject62 {
            client_nonce: None,
            redirect_uri: None,
            role: None,
        }
    }
}


