/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject257 {
    /// The number of bytes to generate (POST body parameter). Defaults to 32 (256 bits).
    #[serde(rename = "bytes", skip_serializing_if = "Option::is_none")]
    pub bytes: Option<i32>,
    /// Encoding format to use. Can be \"hex\" or \"base64\". Defaults to \"base64\".
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
}

impl InlineObject257 {
    pub fn new() -> InlineObject257 {
        InlineObject257 {
            bytes: None,
            format: None,
        }
    }
}


