/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject15 {
    /// Use \"token_period\" instead. If this and \"token_period\" are both specified, only \"token_period\" will be used.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
}

impl InlineObject15 {
    pub fn new() -> InlineObject15 {
        InlineObject15 {
            period: None,
            token_period: None,
        }
    }
}


