/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject162 {
    /// If set to true, disables generating the CRL entirely.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    /// The amount of time the generated CRL should be valid; defaults to 72 hours
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
}

impl InlineObject162 {
    pub fn new() -> InlineObject162 {
        InlineObject162 {
            disable: None,
            expiry: None,
        }
    }
}


