/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject168 {
    /// If set, clients can request certificates for any CN they like. See the documentation for more information.
    #[serde(rename = "allow_any_name", skip_serializing_if = "Option::is_none")]
    pub allow_any_name: Option<bool>,
    /// If set, clients can request certificates for the base domains themselves, e.g. \"example.com\". This is a separate option as in some cases this can be considered a security threat.
    #[serde(rename = "allow_bare_domains", skip_serializing_if = "Option::is_none")]
    pub allow_bare_domains: Option<bool>,
    /// If set, domains specified in \"allowed_domains\" can include glob patterns, e.g. \"ftp*.example.com\". See the documentation for more information.
    #[serde(rename = "allow_glob_domains", skip_serializing_if = "Option::is_none")]
    pub allow_glob_domains: Option<bool>,
    /// If set, IP Subject Alternative Names are allowed. Any valid IP is accepted.
    #[serde(rename = "allow_ip_sans", skip_serializing_if = "Option::is_none")]
    pub allow_ip_sans: Option<bool>,
    /// Whether to allow \"localhost\" as a valid common name in a request
    #[serde(rename = "allow_localhost", skip_serializing_if = "Option::is_none")]
    pub allow_localhost: Option<bool>,
    /// If set, clients can request certificates for subdomains of the CNs allowed by the other role options, including wildcard subdomains. See the documentation for more information.
    #[serde(rename = "allow_subdomains", skip_serializing_if = "Option::is_none")]
    pub allow_subdomains: Option<bool>,
    /// If set, clients can request certificates for subdomains directly beneath these domains, including the wildcard subdomains. See the documentation for more information. This parameter accepts a comma-separated string or list of domains.
    #[serde(rename = "allowed_domains", skip_serializing_if = "Option::is_none")]
    pub allowed_domains: Option<Vec<String>>,
    /// If set, Allowed domains can be specified using identity template policies. Non-templated domains are also permitted.
    #[serde(rename = "allowed_domains_template", skip_serializing_if = "Option::is_none")]
    pub allowed_domains_template: Option<bool>,
    /// If set, an array of allowed other names to put in SANs. These values support globbing and must be in the format <oid>;<type>:<value>. Currently only \"utf8\" is a valid type. All values, including globbing values, must use this syntax, with the exception being a single \"*\" which allows any OID and any value (but type must still be utf8).
    #[serde(rename = "allowed_other_sans", skip_serializing_if = "Option::is_none")]
    pub allowed_other_sans: Option<Vec<String>>,
    /// If set, an array of allowed serial numbers to put in Subject. These values support globbing.
    #[serde(rename = "allowed_serial_numbers", skip_serializing_if = "Option::is_none")]
    pub allowed_serial_numbers: Option<Vec<String>>,
    /// If set, an array of allowed URIs to put in the URI Subject Alternative Names. Any valid URI is accepted, these values support globbing.
    #[serde(rename = "allowed_uri_sans", skip_serializing_if = "Option::is_none")]
    pub allowed_uri_sans: Option<Vec<String>>,
    /// Backend Type
    #[serde(rename = "backend", skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Mark Basic Constraints valid when issuing non-CA certificates.
    #[serde(rename = "basic_constraints_valid_for_non_ca", skip_serializing_if = "Option::is_none")]
    pub basic_constraints_valid_for_non_ca: Option<bool>,
    /// If set, certificates are flagged for client auth use. Defaults to true.
    #[serde(rename = "client_flag", skip_serializing_if = "Option::is_none")]
    pub client_flag: Option<bool>,
    /// If set, certificates are flagged for code signing use. Defaults to false.
    #[serde(rename = "code_signing_flag", skip_serializing_if = "Option::is_none")]
    pub code_signing_flag: Option<bool>,
    /// If set, Country will be set to this value in certificates issued by this role.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<Vec<String>>,
    /// If set, certificates are flagged for email protection use. Defaults to false.
    #[serde(rename = "email_protection_flag", skip_serializing_if = "Option::is_none")]
    pub email_protection_flag: Option<bool>,
    /// If set, only valid host names are allowed for CN and SANs. Defaults to true.
    #[serde(rename = "enforce_hostnames", skip_serializing_if = "Option::is_none")]
    pub enforce_hostnames: Option<bool>,
    /// A comma-separated string or list of extended key usages. Valid values can be found at https://golang.org/pkg/crypto/x509/#ExtKeyUsage -- simply drop the \"ExtKeyUsage\" part of the name. To remove all key usages from being set, set this value to an empty list.
    #[serde(rename = "ext_key_usage", skip_serializing_if = "Option::is_none")]
    pub ext_key_usage: Option<Vec<String>>,
    /// A comma-separated string or list of extended key usage oids.
    #[serde(rename = "ext_key_usage_oids", skip_serializing_if = "Option::is_none")]
    pub ext_key_usage_oids: Option<Vec<String>>,
    /// If set, certificates issued/signed against this role will have Vault leases attached to them. Defaults to \"false\". Certificates can be added to the CRL by \"vault revoke <lease_id>\" when certificates are associated with leases. It can also be done using the \"pki/revoke\" endpoint. However, when lease generation is disabled, invoking \"pki/revoke\" would be the only way to add the certificates to the CRL. When large number of certificates are generated with long lifetimes, it is recommended that lease generation be disabled, as large amount of leases adversely affect the startup time of Vault.
    #[serde(rename = "generate_lease", skip_serializing_if = "Option::is_none")]
    pub generate_lease: Option<bool>,
    /// The number of bits to use. You will almost certainly want to change this if you adjust the key_type.
    #[serde(rename = "key_bits", skip_serializing_if = "Option::is_none")]
    pub key_bits: Option<i32>,
    /// The type of key to use; defaults to RSA. \"rsa\" and \"ec\" are the only valid values.
    #[serde(rename = "key_type", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<KeyType>,
    /// A comma-separated string or list of key usages (not extended key usages). Valid values can be found at https://golang.org/pkg/crypto/x509/#KeyUsage -- simply drop the \"KeyUsage\" part of the name. To remove all key usages from being set, set this value to an empty list.
    #[serde(rename = "key_usage", skip_serializing_if = "Option::is_none")]
    pub key_usage: Option<Vec<String>>,
    /// If set, Locality will be set to this value in certificates issued by this role.
    #[serde(rename = "locality", skip_serializing_if = "Option::is_none")]
    pub locality: Option<Vec<String>>,
    /// The maximum allowed lease duration
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// If set, certificates issued/signed against this role will not be stored in the storage backend. This can improve performance when issuing large numbers of certificates. However, certificates issued in this way cannot be enumerated or revoked, so this option is recommended only for certificates that are non-sensitive, or extremely short-lived. This option implies a value of \"false\" for \"generate_lease\".
    #[serde(rename = "no_store", skip_serializing_if = "Option::is_none")]
    pub no_store: Option<bool>,
    /// The duration before now the cert needs to be created / signed.
    #[serde(rename = "not_before_duration", skip_serializing_if = "Option::is_none")]
    pub not_before_duration: Option<i32>,
    /// If set, O (Organization) will be set to this value in certificates issued by this role.
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Vec<String>>,
    /// If set, OU (OrganizationalUnit) will be set to this value in certificates issued by this role.
    #[serde(rename = "ou", skip_serializing_if = "Option::is_none")]
    pub ou: Option<Vec<String>>,
    /// A comma-separated string or list of policy oids.
    #[serde(rename = "policy_identifiers", skip_serializing_if = "Option::is_none")]
    pub policy_identifiers: Option<Vec<String>>,
    /// If set, Postal Code will be set to this value in certificates issued by this role.
    #[serde(rename = "postal_code", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Vec<String>>,
    /// If set, Province will be set to this value in certificates issued by this role.
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<Vec<String>>,
    /// If set to false, makes the 'common_name' field optional while generating a certificate.
    #[serde(rename = "require_cn", skip_serializing_if = "Option::is_none")]
    pub require_cn: Option<bool>,
    /// If set, certificates are flagged for server auth use. Defaults to true.
    #[serde(rename = "server_flag", skip_serializing_if = "Option::is_none")]
    pub server_flag: Option<bool>,
    /// If set, Street Address will be set to this value in certificates issued by this role.
    #[serde(rename = "street_address", skip_serializing_if = "Option::is_none")]
    pub street_address: Option<Vec<String>>,
    /// The lease duration if no specific lease duration is requested. The lease duration controls the expiration of certificates issued by this backend. Defaults to the value of max_ttl.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// If set, when used with a signing profile, the common name in the CSR will be used. This does *not* include any requested Subject Alternative Names. Defaults to true.
    #[serde(rename = "use_csr_common_name", skip_serializing_if = "Option::is_none")]
    pub use_csr_common_name: Option<bool>,
    /// If set, when used with a signing profile, the SANs in the CSR will be used. This does *not* include the Common Name (cn). Defaults to true.
    #[serde(rename = "use_csr_sans", skip_serializing_if = "Option::is_none")]
    pub use_csr_sans: Option<bool>,
}

impl InlineObject168 {
    pub fn new() -> InlineObject168 {
        InlineObject168 {
            allow_any_name: None,
            allow_bare_domains: None,
            allow_glob_domains: None,
            allow_ip_sans: None,
            allow_localhost: None,
            allow_subdomains: None,
            allowed_domains: None,
            allowed_domains_template: None,
            allowed_other_sans: None,
            allowed_serial_numbers: None,
            allowed_uri_sans: None,
            backend: None,
            basic_constraints_valid_for_non_ca: None,
            client_flag: None,
            code_signing_flag: None,
            country: None,
            email_protection_flag: None,
            enforce_hostnames: None,
            ext_key_usage: None,
            ext_key_usage_oids: None,
            generate_lease: None,
            key_bits: None,
            key_type: None,
            key_usage: None,
            locality: None,
            max_ttl: None,
            no_store: None,
            not_before_duration: None,
            organization: None,
            ou: None,
            policy_identifiers: None,
            postal_code: None,
            province: None,
            require_cn: None,
            server_flag: None,
            street_address: None,
            ttl: None,
            use_csr_common_name: None,
            use_csr_sans: None,
        }
    }
}

/// The type of key to use; defaults to RSA. \"rsa\" and \"ec\" are the only valid values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "rsa")]
    Rsa,
    #[serde(rename = "ec")]
    Ec,
}

