/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject64 {
    /// Comma-separated list of allowed values for redirect_uri
    #[serde(rename = "allowed_redirect_uris", skip_serializing_if = "Option::is_none")]
    pub allowed_redirect_uris: Option<Vec<String>>,
    /// Comma-separated list of 'aud' claims that are valid for login; any match is sufficient
    #[serde(rename = "bound_audiences", skip_serializing_if = "Option::is_none")]
    pub bound_audiences: Option<Vec<String>>,
    /// Use \"token_bound_cidrs\" instead. If this and \"token_bound_cidrs\" are both specified, only \"token_bound_cidrs\" will be used.
    #[serde(rename = "bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub bound_cidrs: Option<Vec<String>>,
    /// Map of claims/values which must match for login
    #[serde(rename = "bound_claims", skip_serializing_if = "Option::is_none")]
    pub bound_claims: Option<serde_json::Value>,
    /// How to interpret values in the map of claims/values (which must match for login): allowed values are 'string' or 'glob'
    #[serde(rename = "bound_claims_type", skip_serializing_if = "Option::is_none")]
    pub bound_claims_type: Option<String>,
    /// The 'sub' claim that is valid for login. Optional.
    #[serde(rename = "bound_subject", skip_serializing_if = "Option::is_none")]
    pub bound_subject: Option<String>,
    /// Mappings of claims (key) that will be copied to a metadata field (value)
    #[serde(rename = "claim_mappings", skip_serializing_if = "Option::is_none")]
    pub claim_mappings: Option<serde_json::Value>,
    /// Duration in seconds of leeway when validating all claims to account for clock skew. Defaults to 60 (1 minute) if set to 0 and can be disabled if set to -1.
    #[serde(rename = "clock_skew_leeway", skip_serializing_if = "Option::is_none")]
    pub clock_skew_leeway: Option<i32>,
    /// Duration in seconds of leeway when validating expiration of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1.
    #[serde(rename = "expiration_leeway", skip_serializing_if = "Option::is_none")]
    pub expiration_leeway: Option<i32>,
    /// The claim to use for the Identity group alias names
    #[serde(rename = "groups_claim", skip_serializing_if = "Option::is_none")]
    pub groups_claim: Option<String>,
    /// Use \"token_max_ttl\" instead. If this and \"token_max_ttl\" are both specified, only \"token_max_ttl\" will be used.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Duration in seconds of leeway when validating not before values of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1.
    #[serde(rename = "not_before_leeway", skip_serializing_if = "Option::is_none")]
    pub not_before_leeway: Option<i32>,
    /// Use \"token_num_uses\" instead. If this and \"token_num_uses\" are both specified, only \"token_num_uses\" will be used.
    #[serde(rename = "num_uses", skip_serializing_if = "Option::is_none")]
    pub num_uses: Option<i32>,
    /// Comma-separated list of OIDC scopes
    #[serde(rename = "oidc_scopes", skip_serializing_if = "Option::is_none")]
    pub oidc_scopes: Option<Vec<String>>,
    /// Use \"token_period\" instead. If this and \"token_period\" are both specified, only \"token_period\" will be used.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<i32>,
    /// Use \"token_policies\" instead. If this and \"token_policies\" are both specified, only \"token_policies\" will be used.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// Type of the role, either 'jwt' or 'oidc'.
    #[serde(rename = "role_type", skip_serializing_if = "Option::is_none")]
    pub role_type: Option<String>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// The maximum lifetime of the generated token
    #[serde(rename = "token_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// Comma-separated list of policies
    #[serde(rename = "token_policies", skip_serializing_if = "Option::is_none")]
    pub token_policies: Option<Vec<String>>,
    /// The initial ttl of the token to generate
    #[serde(rename = "token_ttl", skip_serializing_if = "Option::is_none")]
    pub token_ttl: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    /// Use \"token_ttl\" instead. If this and \"token_ttl\" are both specified, only \"token_ttl\" will be used.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// The claim to use for the Identity entity alias name
    #[serde(rename = "user_claim", skip_serializing_if = "Option::is_none")]
    pub user_claim: Option<String>,
    /// Log received OIDC tokens and claims when debug-level logging is active. Not recommended in production since sensitive information may be present in OIDC responses.
    #[serde(rename = "verbose_oidc_logging", skip_serializing_if = "Option::is_none")]
    pub verbose_oidc_logging: Option<bool>,
}

impl InlineObject64 {
    pub fn new() -> InlineObject64 {
        InlineObject64 {
            allowed_redirect_uris: None,
            bound_audiences: None,
            bound_cidrs: None,
            bound_claims: None,
            bound_claims_type: None,
            bound_subject: None,
            claim_mappings: None,
            clock_skew_leeway: None,
            expiration_leeway: None,
            groups_claim: None,
            max_ttl: None,
            not_before_leeway: None,
            num_uses: None,
            oidc_scopes: None,
            period: None,
            policies: None,
            role_type: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_policies: None,
            token_ttl: None,
            token_type: None,
            ttl: None,
            user_claim: None,
            verbose_oidc_logging: None,
        }
    }
}


