/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject262 {
    /// Deprecated: use \"hash_algorithm\" instead.
    #[serde(rename = "algorithm", skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<String>,
    /// Base64 encoded context for key derivation. Required if key derivation is enabled; currently only available with ed25519 keys.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// Hash algorithm to use (POST body parameter). Valid values are: * sha1 * sha2-224 * sha2-256 * sha2-384 * sha2-512 Defaults to \"sha2-256\". Not valid for all key types, including ed25519.
    #[serde(rename = "hash_algorithm", skip_serializing_if = "Option::is_none")]
    pub hash_algorithm: Option<String>,
    /// The base64-encoded input data
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<String>,
    /// The version of the key to use for signing. Must be 0 (for latest) or a value greater than or equal to the min_encryption_version configured on the key.
    #[serde(rename = "key_version", skip_serializing_if = "Option::is_none")]
    pub key_version: Option<i32>,
    /// The method by which to marshal the signature. The default is 'asn1' which is used by openssl and X.509. It can also be set to 'jws' which is used for JWT signatures; setting it to this will also cause the encoding of the signature to be url-safe base64 instead of using standard base64 encoding. Currently only valid for ECDSA P-256 key types\".
    #[serde(rename = "marshaling_algorithm", skip_serializing_if = "Option::is_none")]
    pub marshaling_algorithm: Option<String>,
    /// Set to 'true' when the input is already hashed. If the key type is 'rsa-2048', 'rsa-3072' or 'rsa-4096', then the algorithm used to hash the input should be indicated by the 'algorithm' parameter.
    #[serde(rename = "prehashed", skip_serializing_if = "Option::is_none")]
    pub prehashed: Option<bool>,
    /// The signature algorithm to use for signing. Currently only applies to RSA key types. Options are 'pss' or 'pkcs1v15'. Defaults to 'pss'
    #[serde(rename = "signature_algorithm", skip_serializing_if = "Option::is_none")]
    pub signature_algorithm: Option<String>,
}

impl InlineObject262 {
    pub fn new() -> InlineObject262 {
        InlineObject262 {
            algorithm: None,
            context: None,
            hash_algorithm: None,
            input: None,
            key_version: None,
            marshaling_algorithm: None,
            prehashed: None,
            signature_algorithm: None,
        }
    }
}


