/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject99 {
    /// The desired increment in seconds to the token expiration
    #[serde(rename = "increment", skip_serializing_if = "Option::is_none")]
    pub increment: Option<i32>,
    /// Token to renew (unused, does not need to be set)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl InlineObject99 {
    pub fn new() -> InlineObject99 {
        InlineObject99 {
            increment: None,
            token: None,
        }
    }
}


