/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject146 {
    /// ID of the group to which this is an alias.
    #[serde(rename = "canonical_id", skip_serializing_if = "Option::is_none")]
    pub canonical_id: Option<String>,
    /// Mount accessor to which this alias belongs to.
    #[serde(rename = "mount_accessor", skip_serializing_if = "Option::is_none")]
    pub mount_accessor: Option<String>,
    /// Alias of the group.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl InlineObject146 {
    pub fn new() -> InlineObject146 {
        InlineObject146 {
            canonical_id: None,
            mount_accessor: None,
            name: None,
        }
    }
}


