/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject108 {
    /// Use \"token_bound_cidrs\" instead. If this and \"token_bound_cidrs\" are both specified, only \"token_bound_cidrs\" will be used.
    #[serde(rename = "bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub bound_cidrs: Option<Vec<String>>,
    /// Use \"token_max_ttl\" instead. If this and \"token_max_ttl\" are both specified, only \"token_max_ttl\" will be used.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Password for this user.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Use \"token_policies\" instead. If this and \"token_policies\" are both specified, only \"token_policies\" will be used.
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Vec<String>>,
    /// Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    #[serde(rename = "token_bound_cidrs", skip_serializing_if = "Option::is_none")]
    pub token_bound_cidrs: Option<Vec<String>>,
    /// If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    #[serde(rename = "token_explicit_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_explicit_max_ttl: Option<i32>,
    /// The maximum lifetime of the generated token
    #[serde(rename = "token_max_ttl", skip_serializing_if = "Option::is_none")]
    pub token_max_ttl: Option<i32>,
    /// If true, the 'default' policy will not automatically be added to generated tokens
    #[serde(rename = "token_no_default_policy", skip_serializing_if = "Option::is_none")]
    pub token_no_default_policy: Option<bool>,
    /// The maximum number of times a token may be used, a value of zero means unlimited
    #[serde(rename = "token_num_uses", skip_serializing_if = "Option::is_none")]
    pub token_num_uses: Option<i32>,
    /// If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. \"24h\").
    #[serde(rename = "token_period", skip_serializing_if = "Option::is_none")]
    pub token_period: Option<i32>,
    /// Comma-separated list of policies
    #[serde(rename = "token_policies", skip_serializing_if = "Option::is_none")]
    pub token_policies: Option<Vec<String>>,
    /// The initial ttl of the token to generate
    #[serde(rename = "token_ttl", skip_serializing_if = "Option::is_none")]
    pub token_ttl: Option<i32>,
    /// The type of token to generate, service or batch
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    /// Use \"token_ttl\" instead. If this and \"token_ttl\" are both specified, only \"token_ttl\" will be used.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl InlineObject108 {
    pub fn new() -> InlineObject108 {
        InlineObject108 {
            bound_cidrs: None,
            max_ttl: None,
            password: None,
            policies: None,
            token_bound_cidrs: None,
            token_explicit_max_ttl: None,
            token_max_ttl: None,
            token_no_default_policy: None,
            token_num_uses: None,
            token_period: None,
            token_policies: None,
            token_ttl: None,
            token_type: None,
            ttl: None,
        }
    }
}


