/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject184 {
    /// The versions to unarchive. The versions will be restored and their data will be returned on normal get requests.
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<i32>>,
}

impl InlineObject184 {
    pub fn new() -> InlineObject184 {
        InlineObject184 {
            versions: None,
        }
    }
}


