/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject12 {
    /// Impose secret_id to be presented when logging in using this role.
    #[serde(rename = "bind_secret_id", skip_serializing_if = "Option::is_none")]
    pub bind_secret_id: Option<bool>,
}

impl InlineObject12 {
    pub fn new() -> InlineObject12 {
        InlineObject12 {
            bind_secret_id: None,
        }
    }
}


